; New song, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Newsong_Start
	db "AT20"
	dw Newsong_ArpeggioTable	; The address of the Arpeggio table.
	dw Newsong_PitchTable	; The address of the Pitch table.
	dw Newsong_InstrumentTable	; The address of the Instrument table.
	dw Newsong_EffectBlockTable	; The address of the Effect Block table.

; The addresses of each Subsong:
	dw Newsong_Subsong0_Start

; Declares all the Arpeggios.
Newsong_ArpeggioTable

; Declares all the Pitches.
Newsong_PitchTable

; Declares all the Instruments.
Newsong_InstrumentTable
	dw Newsong_EmptyInstrument
	dw Newsong_Instrument1

Newsong_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Newsong_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Newsong_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.
