; Sound effects, Sound effects, format v2.0.

; Generated by Arkos Tracker 3.

MainSoundEffects
MainSoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
MainSoundEffectsDisarkPointerRegionStart0
    dw MainSoundEffects_Sound1    ; Sound effect 1 at index 1.
    dw MainSoundEffects_Sound2    ; Sound effect 2 at index 2.
    dw MainSoundEffects_Sound3    ; Sound effect 3 at index 3.
    dw MainSoundEffects_Sound4    ; Sound effect 4 at index 4.
    dw MainSoundEffects_Sound5    ; Sound effect 5 at index 5.
MainSoundEffectsDisarkPointerRegionEnd0

MainSoundEffectsDisarkByteRegionStart1
; Sound effect 1.
MainSoundEffects_Sound1
    db 0    ; Speed

    db 189    ; Soft only. Volume: 15.
    db 1    ; Noise: 1.
    dw 95    ; Software period.

    db 189    ; Soft only. Volume: 15.
    db 1    ; Noise: 1.
    dw 99    ; Software period.

    db 177    ; Soft only. Volume: 12.
    db 1    ; Noise: 1.
    dw 102    ; Software period.

    db 173    ; Soft only. Volume: 11.
    db 1    ; Noise: 1.
    dw 106    ; Software period.

    db 4    ; End of the sound effect.

; Sound effect 2.
MainSoundEffects_Sound2
    db 1    ; Speed

    db 189    ; Soft only. Volume: 15.
    db 1    ; Noise: 1.
    dw 301    ; Software period.

    db 189    ; Soft only. Volume: 15.
