REM Conformance: the asset pipeline (tools/img2cpc.py, tools/tmx2bas.py) end
REM to end. The includes under assets/ were generated from PNG/TMX sources
REM (tools/build_assets.sh); this draws them with the library and checks the
REM screen bytes (PeekScreen) against values worked out here, from the pixel
REM formulas the sources were drawn with (assets/make_sources.py) and the
REM hardware's pixel-to-bit layout -- not from the generated bytes -- plus
REM the tile map arrays, the constants and the palette arrays.
REM
REM Pixel patterns (x, y in pixels of the source image):
REM   plain sprite   pen (x + k*y) AND (npens-1), k = 2 (mode 1), 3 (mode 0)
REM   masked sprite  transparent where x+y is even, else 1 + (x+2*y) MOD (npens-1)
REM   picture        cell (cx, cy) shows kind (cx + 2*cy) MOD 3 = tile 0..2, whose
REM                  pixel (x, y) has pen ((kind+1)*x + y) AND 3
REM Only failures are listed; the passes are counted.

#include <cpc.bas>
#include <cpcbuild/display.bas>
#include <cpcbuild/sprites.bas>
#include <cpcbuild/tiles.bas>
#include "assets/spr1.bas"
#include "assets/msk1.bas"
#include "assets/pic1.bas"
#include "assets/level.bas"
#include "assets/spr0.bas"
#include "assets/msk0.bas"

DIM results$ AS STRING
DIM npass AS UINTEGER = 0
SUB CHK(name AS STRING, gotv AS STRING, wantv AS STRING)
  IF gotv = wantv THEN
    npass = npass + 1
  ELSE
    results$ = results$ + "FAIL " + name + " got=" + gotv + " want=" + wantv + CHR$ 13
  END IF
END SUB

SUB ClearScr
  ASM
  ld hl, $C000
  ld de, $C001
  ld bc, $3FFF
  ld (hl), 0
  ldir
  END ASM
END SUB

REM The screen bits of pixel n (0 = leftmost) of a byte, in pen `pen`.
FUNCTION Enc(mode AS UBYTE, n AS UBYTE, pen AS UBYTE) AS UBYTE
  DIM v AS UBYTE
  v = ((pen bAND 1) << (7 - n)) bOR (((pen >> 1) bAND 1) << (3 - n))
  IF mode = 0 THEN
    v = v bOR (((pen >> 2) bAND 1) << (5 - n)) bOR (((pen >> 3) bAND 1) << (1 - n))
  END IF
  RETURN v
END FUNCTION

FUNCTION PlainPen(mode AS UBYTE, px AS UBYTE, py AS UBYTE) AS UBYTE
  IF mode = 0 THEN RETURN (px + 3 * py) bAND 15
  RETURN (px + 2 * py) bAND 3
END FUNCTION

REM 255 = transparent
FUNCTION MaskPen(mode AS UBYTE, px AS UBYTE, py AS UBYTE) AS UBYTE
  IF ((px + py) bAND 1) = 0 THEN RETURN 255
  IF mode = 0 THEN RETURN 1 + (px + 2 * py) MOD 15
  RETURN 1 + (px + 2 * py) MOD 3
END FUNCTION

CONST BG AS UBYTE = $A5

SUB FillBg(x0 AS UBYTE, y0 AS UBYTE, wb AS UBYTE, h AS UBYTE)
  DIM r, b AS UBYTE
  FOR r = 0 TO h - 1
    FOR b = 0 TO wb - 1
      PokeScreen(x0 + b, y0 + r, BG)
    NEXT b
  NEXT r
END SUB

REM Bytes of the wb x h block at (x0, y0) that differ from the pattern.
FUNCTION SprBad(mode AS UBYTE, x0 AS UBYTE, y0 AS UBYTE, wb AS UBYTE, h AS UBYTE, masked AS UBYTE) AS UINTEGER
  DIM r, b, n, ppb, p, pix, msk, want AS UBYTE
  DIM bad AS UINTEGER = 0
  ppb = 4
  IF mode = 0 THEN ppb = 2
  FOR r = 0 TO h - 1
    FOR b = 0 TO wb - 1
      pix = 0
      msk = 0
      FOR n = 0 TO ppb - 1
        IF masked THEN
          p = MaskPen(mode, b * ppb + n, r)
          IF p = 255 THEN
            msk = msk bOR Enc(mode, n, 255)
          ELSE
            pix = pix bOR Enc(mode, n, p)
          END IF
        ELSE
          pix = pix bOR Enc(mode, n, PlainPen(mode, b * ppb + n, r))
        END IF
      NEXT n
      IF masked THEN
        want = (BG bAND msk) bOR pix
      ELSE
        want = pix
      END IF
      IF PeekScreen(x0 + b, y0 + r) <> want THEN bad = bad + 1
    NEXT b
  NEXT r
  RETURN bad
END FUNCTION

REM Bytes of the 4 x 2 cell picture at tile cell (ox, oy) (mode 1) that differ.
FUNCTION PicBad(ox AS UBYTE, oy AS UBYTE) AS UINTEGER
  DIM cx, cy, r, b, n, k, v AS UBYTE
  DIM bad AS UINTEGER = 0
  FOR cy = 0 TO 1
    FOR cx = 0 TO 3
      k = (cx + 2 * cy) MOD 3
      FOR r = 0 TO 7
        FOR b = 0 TO 1
          v = 0
          FOR n = 0 TO 3
            v = v bOR Enc(1, n, ((k + 1) * (b * 4 + n) + r) bAND 3)
          NEXT n
          IF PeekScreen((ox + cx) * 2 + b, (oy + cy) * 8 + r) <> v THEN bad = bad + 1
        NEXT b
      NEXT r
    NEXT cx
  NEXT cy
  RETURN bad
END FUNCTION

DIM expPal1(3) AS UBYTE => {0, 26, 6, 18}

REM --- mode 1 ---
Mode 1
ScreenInit()
ClearScr()

CHK("spr1_consts", STR$(a_spr1_W) + "," + STR$(a_spr1_H) + "," + STR$(a_spr1_FRAMES) + "," + STR$(a_spr1_SIZE), "2,4,1,8")
CHK("msk1_consts", STR$(a_msk1_W) + "," + STR$(a_msk1_H) + "," + STR$(a_msk1_FRAMES) + "," + STR$(a_msk1_SIZE), "2,4,1,16")
CHK("pic_consts", STR$(a_pic_COUNT) + "," + STR$(a_pic_MAPW) + "," + STR$(a_pic_MAPH), "3,4,2")
CHK("map_consts", STR$(a_map_W) + "," + STR$(a_map_H), "4,2")

PutSprite(10, 20, a_spr1_W, a_spr1_H, @a_spr1(0))
CHK("m1_sprite", STR$(SprBad(1, 10, 20, 2, 4, 0)), "0")
CHK("m1_sprite_left_edge", STR$(PeekScreen(9, 20)), "0")
CHK("m1_sprite_right_edge", STR$(PeekScreen(12, 23)), "0")

FillBg(30, 40, 2, 4)
PutSpriteMasked(30, 40, a_msk1_W, a_msk1_H, @a_msk1(0))
CHK("m1_masked", STR$(SprBad(1, 30, 40, 2, 4, 1)), "0")
CHK("m1_masked_left_edge", STR$(PeekScreen(29, 40)), "0")

SetTileSet(@a_pic(0))
TileMap(@a_pic_MAP(0), 10, 12, a_pic_MAPW, a_pic_MAPH)
CHK("m1_pic_map", STR$(PicBad(10, 12)), "0")
TileMap(@a_map(0), 3, 5, a_map_W, a_map_H)
CHK("m1_tmx_map", STR$(PicBad(3, 5)), "0")

DIM i AS UBYTE
DIM bad AS UBYTE = 0
FOR i = 0 TO 7
  IF a_map(i) <> (i MOD 4 + 2 * (i / 4)) MOD 3 THEN bad = bad + 1
  IF a_pic_MAP(i) <> (i MOD 4 + 2 * (i / 4)) MOD 3 THEN bad = bad + 1
NEXT i
CHK("map_arrays", STR$(bad), "0")

bad = 0
FOR i = 0 TO 3
  IF a_spr1_pal(i) <> expPal1(i) THEN bad = bad + 1
  IF a_msk1_pal(i) <> expPal1(i) THEN bad = bad + 1
  IF a_pic_pal(i) <> expPal1(i) THEN bad = bad + 1
NEXT i
CHK("m1_palettes", STR$(bad), "0")
CHK("m1_pens", STR$(a_spr1_PENS) + "," + STR$(a_msk1_PENS) + "," + STR$(a_pic_PENS), "4,4,4")

REM --- mode 0 ---
Mode 0
ScreenInit()
ClearScr()
CHK("spr0_consts", STR$(a_spr0_W) + "," + STR$(a_spr0_H) + "," + STR$(a_spr0_FRAMES) + "," + STR$(a_spr0_SIZE), "8,4,1,32")
CHK("msk0_consts", STR$(a_msk0_W) + "," + STR$(a_msk0_H) + "," + STR$(a_msk0_FRAMES) + "," + STR$(a_msk0_SIZE), "4,4,1,32")

PutSprite(5, 10, a_spr0_W, a_spr0_H, @a_spr0(0))
CHK("m0_sprite", STR$(SprBad(0, 5, 10, 8, 4, 0)), "0")
CHK("m0_sprite_edges", STR$(PeekScreen(4, 10)) + "," + STR$(PeekScreen(13, 13)), "0,0")

FillBg(20, 50, 4, 4)
PutSpriteMasked(20, 50, a_msk0_W, a_msk0_H, @a_msk0(0))
CHK("m0_masked", STR$(SprBad(0, 20, 50, 4, 4, 1)), "0")

REM pens 0-15 are firmware colours (7 * pen) MOD 27, in pen order
bad = 0
FOR i = 0 TO 15
  IF a_spr0_pal(i) <> (i * 7) MOD 27 THEN bad = bad + 1
  IF a_msk0_pal(i) <> (i * 7) MOD 27 THEN bad = bad + 1
NEXT i
CHK("m0_palettes", STR$(bad), "0")
CHK("m0_pens", STR$(a_spr0_PENS) + "," + STR$(a_msk0_PENS), "16,16")

Mode 1
ScreenInit()
CLS
PRINT AT 0, 0;
PRINT "PASS "; npass; " checks"
PRINT results$; CHR$ 13; "DONE"
END
