' bounce_music.bas -- Arkos AKG song, converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @bounce_music to MusicInit(@bounce_music, subsong).

#ifndef __AKS_BOUNCE_MUSIC__
#define __AKS_BOUNCE_MUSIC__

asm
    jp __aks_bounce_music_end
end asm
bounce_music:
asm
    ; bounce music, AKG format, v1.0.

    ; Generated by Arkos Tracker 3.

bounce_music_Start:
bounce_music_StartDisarkGenerateExternalLabel:

bounce_music_DisarkByteRegionStart0:
    db "AT30"
bounce_music_DisarkPointerRegionStart1:
    dw bounce_music_ArpeggioTable    ; The address of the Arpeggio table.
    dw bounce_music_PitchTable    ; The address of the Pitch table.
    dw bounce_music_InstrumentTable    ; The address of the Instrument table.
    dw bounce_music_EffectBlockTable    ; The address of the Effect Block table.
bounce_music_DisarkPointerRegionEnd1:

    ; The addresses of each Subsong.
bounce_music_DisarkPointerRegionStart2:
    dw bounce_music_Subsong0_Start
bounce_music_DisarkPointerRegionEnd2:

    ; Declares all the Arpeggios.
bounce_music_ArpeggioTable:
bounce_music_DisarkPointerRegionStart3:
bounce_music_DisarkPointerRegionEnd3:

    ; Declares all the Pitches.
bounce_music_PitchTable:
bounce_music_DisarkPointerRegionStart4:
bounce_music_DisarkPointerRegionEnd4:

    ; Declares all the Instruments.
bounce_music_InstrumentTable:
bounce_music_DisarkPointerRegionStart5:
    dw bounce_music_EmptyInstrument
    dw bounce_music_Instrument1
    dw bounce_music_Instrument2
bounce_music_DisarkPointerRegionEnd5:

bounce_music_EmptyInstrument:
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

bounce_music_Instrument1:
    db 1    ; The speed (>0, 0 for 256).

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.

bounce_music_Instrument2:
    db 1    ; The speed (>0, 0 for 256).

bounce_music_Instrument2_Loop:
    db 241    ; Soft only. Volume: 14. Volume only.

    db 7    ; Loop.
bounce_music_DisarkWordForceReference6:
    dw bounce_music_Instrument2_Loop    ; Loop here.

    ; The indexes of the effect blocks used by this song.
bounce_music_EffectBlockTable:
bounce_music_DisarkPointerRegionStart7:
    dw bounce_music_EffectBlock_P5P0P8    ; Index 0
bounce_music_DisarkPointerRegionEnd7:
bounce_music_EffectBlock_P5P0P8:
    db 5
    db 0
    db 8

bounce_music_DisarkByteRegionEnd0:

    ; Subsong 0
    ; ----------------------
bounce_music_Subsong0_DisarkByteRegionStart0:
bounce_music_Subsong0_Start:
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 1    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 0    ; End index (>=0).
    db 8    ; Initial speed (>=0).
    db 10    ; Base note index (>=0).

bounce_music_Subsong0_Linker:
bounce_music_Subsong0_DisarkPointerRegionStart1:
    ; Position 0
bounce_music_Subsong0_Linker_Loop:
    dw bounce_music_Subsong0_Track0
    dw bounce_music_Subsong0_Track1
    dw bounce_music_Subsong0_Track2
    dw bounce_music_Subsong0_LinkerBlock0
bounce_music_Subsong0_DisarkPointerRegionEnd1:
    dw 0    ; Loop.
bounce_music_Subsong0_DisarkWordForceReference2:
    dw bounce_music_Subsong0_Linker_Loop

bounce_music_Subsong0_LinkerBlock0:
    db 32    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
bounce_music_Subsong0_DisarkWordForceReference3:
    dw bounce_music_Subsong0_SpeedTrack0    ; SpeedTrack address.
bounce_music_Subsong0_DisarkWordForceReference4:
    dw bounce_music_Subsong0_EventTrack0    ; EventTrack address.

bounce_music_Subsong0_Track0:
    db 61
    db 127    ; Waits for 128 lines.

bounce_music_Subsong0_Track1:
    db 246
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 50
    db 47
    db 50
    db 54
    db 50
    db 47
    db 50
    db 55
    db 50
    db 47
    db 50
    db 55
    db 50
    db 47
    db 50
    db 54
    db 50
    db 45
    db 50
    db 54
    db 50
    db 45
    db 50
    db 52
    db 49
    db 45
    db 49
    db 52
    db 49
    db 45
    db 49
    db 61
    db 127    ; Waits for 128 lines.

bounce_music_Subsong0_Track2:
    db 215
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 30
    db 60    ; Waits for 1 line.

    db 23
    db 60    ; Waits for 1 line.

    db 30
    db 60    ; Waits for 1 line.

    db 19
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 19
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 21
    db 60    ; Waits for 1 line.

    db 28
    db 60    ; Waits for 1 line.

    db 21
    db 60    ; Waits for 1 line.

    db 28
    db 61
    db 127    ; Waits for 128 lines.

    ; The speed tracks
bounce_music_Subsong0_SpeedTrack0:
    db 255    ; Wait for 128 lines.

    ; The event tracks
bounce_music_Subsong0_EventTrack0:
    db 255    ; Wait for 128 lines.

bounce_music_Subsong0_DisarkByteRegionEnd0:
__aks_bounce_music_end:
end asm

#endif
