' bounce_quiet.bas -- Arkos AKG song, converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @bounce_quiet to MusicInit(@bounce_quiet, subsong).

#ifndef __AKS_BOUNCE_QUIET__
#define __AKS_BOUNCE_QUIET__

asm
    jp __aks_bounce_quiet_end
end asm
bounce_quiet:
asm
    ; bounce quiet, AKG format, v1.0.

    ; Generated by Arkos Tracker 3.

bounce_quiet_Start:
bounce_quiet_StartDisarkGenerateExternalLabel:

bounce_quiet_DisarkByteRegionStart0:
    db "AT30"
bounce_quiet_DisarkPointerRegionStart1:
    dw bounce_quiet_ArpeggioTable    ; The address of the Arpeggio table.
    dw bounce_quiet_PitchTable    ; The address of the Pitch table.
    dw bounce_quiet_InstrumentTable    ; The address of the Instrument table.
    dw bounce_quiet_EffectBlockTable    ; The address of the Effect Block table.
bounce_quiet_DisarkPointerRegionEnd1:

    ; The addresses of each Subsong.
bounce_quiet_DisarkPointerRegionStart2:
    dw bounce_quiet_Subsong0_Start
bounce_quiet_DisarkPointerRegionEnd2:

    ; Declares all the Arpeggios.
bounce_quiet_ArpeggioTable:
bounce_quiet_DisarkPointerRegionStart3:
bounce_quiet_DisarkPointerRegionEnd3:

    ; Declares all the Pitches.
bounce_quiet_PitchTable:
bounce_quiet_DisarkPointerRegionStart4:
bounce_quiet_DisarkPointerRegionEnd4:

    ; Declares all the Instruments.
bounce_quiet_InstrumentTable:
bounce_quiet_DisarkPointerRegionStart5:
    dw bounce_quiet_EmptyInstrument
bounce_quiet_DisarkPointerRegionEnd5:

bounce_quiet_EmptyInstrument:
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

    ; The indexes of the effect blocks used by this song.
bounce_quiet_EffectBlockTable:

bounce_quiet_DisarkByteRegionEnd0:

    ; Subsong 0
    ; ----------------------
bounce_quiet_Subsong0_DisarkByteRegionStart0:
bounce_quiet_Subsong0_Start:
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 1    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 0    ; End index (>=0).
    db 8    ; Initial speed (>=0).
    db 0    ; Base note index (>=0).

bounce_quiet_Subsong0_Linker:
bounce_quiet_Subsong0_DisarkPointerRegionStart1:
    ; Position 0
bounce_quiet_Subsong0_Linker_Loop:
    dw bounce_quiet_Subsong0_Track0
    dw bounce_quiet_Subsong0_Track0
    dw bounce_quiet_Subsong0_Track0
    dw bounce_quiet_Subsong0_LinkerBlock0
bounce_quiet_Subsong0_DisarkPointerRegionEnd1:
    dw 0    ; Loop.
bounce_quiet_Subsong0_DisarkWordForceReference2:
    dw bounce_quiet_Subsong0_Linker_Loop

bounce_quiet_Subsong0_LinkerBlock0:
    db 8    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
bounce_quiet_Subsong0_DisarkWordForceReference3:
    dw bounce_quiet_Subsong0_SpeedTrack0    ; SpeedTrack address.
bounce_quiet_Subsong0_DisarkWordForceReference4:
    dw bounce_quiet_Subsong0_EventTrack0    ; EventTrack address.

bounce_quiet_Subsong0_Track0:
    db 61
    db 127    ; Waits for 128 lines.

    ; The speed tracks
bounce_quiet_Subsong0_SpeedTrack0:
    db 255    ; Wait for 128 lines.

    ; The event tracks
bounce_quiet_Subsong0_EventTrack0:
    db 255    ; Wait for 128 lines.

bounce_quiet_Subsong0_DisarkByteRegionEnd0:
__aks_bounce_quiet_end:
end asm

#endif
