' bounce_sfx.bas -- Arkos sound effects (AKX), converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @bounce_sfx to SfxInit(@bounce_sfx).

#ifndef __AKS_BOUNCE_SFX__
#define __AKS_BOUNCE_SFX__

asm
    jp __aks_bounce_sfx_end
end asm
bounce_sfx:
asm
    ; bounce sfx, Sound effects, format v2.0.

    ; Generated by Arkos Tracker 3.

bounce_sfx_SoundEffects:
bounce_sfx_SoundEffectsDisarkGenerateExternalLabel:

    ; The sound effects, starting at 1.
bounce_sfx_SoundEffectsDisarkPointerRegionStart0:
    dw bounce_sfx_SoundEffects_Sound1    ; Sound effect 1 at index 1.
    dw bounce_sfx_SoundEffects_Sound2    ; Sound effect 2 at index 2.
    dw bounce_sfx_SoundEffects_Sound3    ; Sound effect 3 at index 3.
    dw bounce_sfx_SoundEffects_Sound4    ; Sound effect 4 at index 4.
    dw bounce_sfx_SoundEffects_Sound5    ; Sound effect 5 at index 5.
    dw bounce_sfx_SoundEffects_Sound6    ; Sound effect 6 at index 6.
    dw bounce_sfx_SoundEffects_Sound7    ; Sound effect 7 at index 7.
    dw bounce_sfx_SoundEffects_Sound8    ; Sound effect 8 at index 8.
bounce_sfx_SoundEffectsDisarkPointerRegionEnd0:

bounce_sfx_SoundEffectsDisarkByteRegionStart1:
    ; Sound effect 1.
bounce_sfx_SoundEffects_Sound1:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 119    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 119    ; Software period.

    db 37    ; Soft only. Volume: 9.
    dw 119    ; Software period.

    db 25    ; Soft only. Volume: 6.
    dw 119    ; Software period.

    db 17    ; Soft only. Volume: 4.
    dw 119    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 119    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 119    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 2.
bounce_sfx_SoundEffects_Sound2:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 95    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 95    ; Software period.

    db 41    ; Soft only. Volume: 10.
    dw 95    ; Software period.

    db 25    ; Soft only. Volume: 6.
    dw 95    ; Software period.

    db 17    ; Soft only. Volume: 4.
    dw 95    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 95    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 95    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 3.
bounce_sfx_SoundEffects_Sound3:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 71    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 71    ; Software period.

    db 37    ; Soft only. Volume: 9.
    dw 71    ; Software period.

    db 29    ; Soft only. Volume: 7.
    dw 71    ; Software period.

    db 17    ; Soft only. Volume: 4.
    dw 71    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 71    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 71    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 4.
bounce_sfx_SoundEffects_Sound4:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 53    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 53    ; Software period.

    db 41    ; Soft only. Volume: 10.
    dw 53    ; Software period.

    db 29    ; Soft only. Volume: 7.
    dw 53    ; Software period.

    db 17    ; Soft only. Volume: 4.
    dw 53    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 53    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 53    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 5.
bounce_sfx_SoundEffects_Sound5:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 239    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 239    ; Software period.

    db 37    ; Soft only. Volume: 9.
    dw 239    ; Software period.

    db 25    ; Soft only. Volume: 6.
    dw 239    ; Software period.

    db 21    ; Soft only. Volume: 5.
    dw 239    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 239    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 239    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 6.
bounce_sfx_SoundEffects_Sound6:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 190    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 190    ; Software period.

    db 41    ; Soft only. Volume: 10.
    dw 190    ; Software period.

    db 25    ; Soft only. Volume: 6.
    dw 190    ; Software period.

    db 21    ; Soft only. Volume: 5.
    dw 190    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 190    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 190    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 7.
bounce_sfx_SoundEffects_Sound7:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 142    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 142    ; Software period.

    db 37    ; Soft only. Volume: 9.
    dw 142    ; Software period.

    db 29    ; Soft only. Volume: 7.
    dw 142    ; Software period.

    db 21    ; Soft only. Volume: 5.
    dw 142    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 142    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 142    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 8.
bounce_sfx_SoundEffects_Sound8:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 106    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 106    ; Software period.

    db 41    ; Soft only. Volume: 10.
    dw 106    ; Software period.

    db 29    ; Soft only. Volume: 7.
    dw 106    ; Software period.

    db 21    ; Soft only. Volume: 5.
    dw 106    ; Software period.

    db 9    ; Soft only. Volume: 2.
    dw 106    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 106    ; Software period.

    db 4    ; End of the sound effect.

bounce_sfx_SoundEffectsDisarkByteRegionEnd1:
__aks_bounce_sfx_end:
end asm

#endif
