' sf_game.bas -- Arkos AKG song, converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @sf_game to MusicInit(@sf_game, subsong).

#ifndef __AKS_SF_GAME__
#define __AKS_SF_GAME__

asm
    jp __aks_sf_game_end
end asm
sf_game:
asm
    ; starfall game, AKG format, v1.0.

    ; Generated by Arkos Tracker 3.

sf_game_Start:
sf_game_StartDisarkGenerateExternalLabel:

sf_game_DisarkByteRegionStart0:
    db "AT30"
sf_game_DisarkPointerRegionStart1:
    dw sf_game_ArpeggioTable    ; The address of the Arpeggio table.
    dw sf_game_PitchTable    ; The address of the Pitch table.
    dw sf_game_InstrumentTable    ; The address of the Instrument table.
    dw sf_game_EffectBlockTable    ; The address of the Effect Block table.
sf_game_DisarkPointerRegionEnd1:

    ; The addresses of each Subsong.
sf_game_DisarkPointerRegionStart2:
    dw sf_game_Subsong0_Start
sf_game_DisarkPointerRegionEnd2:

    ; Declares all the Arpeggios.
sf_game_ArpeggioTable:
sf_game_DisarkPointerRegionStart3:
sf_game_DisarkPointerRegionEnd3:

    ; Declares all the Pitches.
sf_game_PitchTable:
sf_game_DisarkPointerRegionStart4:
sf_game_DisarkPointerRegionEnd4:

    ; Declares all the Instruments.
sf_game_InstrumentTable:
sf_game_DisarkPointerRegionStart5:
    dw sf_game_EmptyInstrument
    dw sf_game_Instrument1
    dw sf_game_Instrument2
sf_game_DisarkPointerRegionEnd5:

sf_game_EmptyInstrument:
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

sf_game_Instrument1:
    db 1    ; The speed (>0, 0 for 256).

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

sf_game_Instrument1_Loop:
    db 209    ; Soft only. Volume: 10. Volume only.

    db 7    ; Loop.
sf_game_DisarkWordForceReference6:
    dw sf_game_Instrument1_Loop    ; Loop here.

sf_game_Instrument2:
    db 1    ; The speed (>0, 0 for 256).

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.

    ; The indexes of the effect blocks used by this song.
sf_game_EffectBlockTable:
sf_game_DisarkPointerRegionStart7:
    dw sf_game_EffectBlock_P5P2P8    ; Index 0
sf_game_DisarkPointerRegionEnd7:
sf_game_EffectBlock_P5P2P8:
    db 5
    db 2
    db 8

sf_game_DisarkByteRegionEnd0:

    ; Subsong 0
    ; ----------------------
sf_game_Subsong0_DisarkByteRegionStart0:
sf_game_Subsong0_Start:
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 1    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 1    ; End index (>=0).
    db 6    ; Initial speed (>=0).
    db 12    ; Base note index (>=0).

sf_game_Subsong0_Linker:
sf_game_Subsong0_DisarkPointerRegionStart1:
    ; Position 0
sf_game_Subsong0_Linker_Loop:
    dw sf_game_Subsong0_Track0
    dw sf_game_Subsong0_Track1
    dw sf_game_Subsong0_Track2
    dw sf_game_Subsong0_LinkerBlock0
    ; Position 1
    dw sf_game_Subsong0_Track0
    dw sf_game_Subsong0_Track3
    dw sf_game_Subsong0_Track2
    dw sf_game_Subsong0_LinkerBlock0
sf_game_Subsong0_DisarkPointerRegionEnd1:
    dw 0    ; Loop.
sf_game_Subsong0_DisarkWordForceReference2:
    dw sf_game_Subsong0_Linker_Loop

sf_game_Subsong0_LinkerBlock0:
    db 32    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
sf_game_Subsong0_DisarkWordForceReference3:
    dw sf_game_Subsong0_SpeedTrack0    ; SpeedTrack address.
sf_game_Subsong0_DisarkWordForceReference4:
    dw sf_game_Subsong0_EventTrack0    ; EventTrack address.

sf_game_Subsong0_Track0:
    db 61
    db 127    ; Waits for 128 lines.

sf_game_Subsong0_Track1:
    db 244
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 45
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 50
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 47
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 47
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 44
    db 61
    db 127    ; Waits for 128 lines.

sf_game_Subsong0_Track2:
    db 213
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 21
    db 33
    db 21
    db 21
    db 33
    db 21
    db 21
    db 17
    db 17
    db 29
    db 17
    db 17
    db 29
    db 17
    db 17
    db 19
    db 19
    db 31
    db 19
    db 19
    db 31
    db 19
    db 19
    db 16
    db 16
    db 28
    db 16
    db 16
    db 28
    db 16
    db 16
    db 61
    db 127    ; Waits for 128 lines.

sf_game_Subsong0_Track3:
    db 237
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 48
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 52
    db 60    ; Waits for 1 line.

    db 45
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 48
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 53
    db 60    ; Waits for 1 line.

    db 47
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 50
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 55
    db 60    ; Waits for 1 line.

    db 44
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 47
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 52
    db 61
    db 127    ; Waits for 128 lines.

    ; The speed tracks
sf_game_Subsong0_SpeedTrack0:
    db 255    ; Wait for 128 lines.

    ; The event tracks
sf_game_Subsong0_EventTrack0:
    db 255    ; Wait for 128 lines.

sf_game_Subsong0_DisarkByteRegionEnd0:
__aks_sf_game_end:
end asm

#endif
