' Generated by img2cpc.py --mode 0 --name shots --sprite --frame 2x4 --palette-file games/shooter/assets/starfall.pal --no-palette games/shooter/assets/shots.png -o games/shooter/assets/shots.bas
' Source: games/shooter/assets/shots.png, 4x4 pixels, mode 0
' 2 frame(s) of 1 bytes x 4 lines, 4 bytes each
' Do not edit; regenerate with tools/build_assets.sh.

DIM shots(7) AS UBYTE => { _
    $80, $80, $08, $08, $20, $A0, $20, $A0 _
}

CONST shots_W AS UBYTE = 1

CONST shots_H AS UBYTE = 4

CONST shots_FRAMES AS UBYTE = 2

CONST shots_SIZE AS UBYTE = 4
