' sf_title.bas -- Arkos AKG song, converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @sf_title to MusicInit(@sf_title, subsong).

#ifndef __AKS_SF_TITLE__
#define __AKS_SF_TITLE__

asm
    jp __aks_sf_title_end
end asm
sf_title:
asm
    ; starfall title, AKG format, v1.0.

    ; Generated by Arkos Tracker 3.

sf_title_Start:
sf_title_StartDisarkGenerateExternalLabel:

sf_title_DisarkByteRegionStart0:
    db "AT30"
sf_title_DisarkPointerRegionStart1:
    dw sf_title_ArpeggioTable    ; The address of the Arpeggio table.
    dw sf_title_PitchTable    ; The address of the Pitch table.
    dw sf_title_InstrumentTable    ; The address of the Instrument table.
    dw sf_title_EffectBlockTable    ; The address of the Effect Block table.
sf_title_DisarkPointerRegionEnd1:

    ; The addresses of each Subsong.
sf_title_DisarkPointerRegionStart2:
    dw sf_title_Subsong0_Start
sf_title_DisarkPointerRegionEnd2:

    ; Declares all the Arpeggios.
sf_title_ArpeggioTable:
sf_title_DisarkPointerRegionStart3:
sf_title_DisarkPointerRegionEnd3:

    ; Declares all the Pitches.
sf_title_PitchTable:
sf_title_DisarkPointerRegionStart4:
sf_title_DisarkPointerRegionEnd4:

    ; Declares all the Instruments.
sf_title_InstrumentTable:
sf_title_DisarkPointerRegionStart5:
    dw sf_title_EmptyInstrument
    dw sf_title_Instrument1
    dw sf_title_Instrument2
sf_title_DisarkPointerRegionEnd5:

sf_title_EmptyInstrument:
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

sf_title_Instrument1:
    db 1    ; The speed (>0, 0 for 256).

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.

sf_title_Instrument2:
    db 1    ; The speed (>0, 0 for 256).

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

sf_title_Instrument2_Loop:
    db 225    ; Soft only. Volume: 12. Volume only.

    db 7    ; Loop.
sf_title_DisarkWordForceReference6:
    dw sf_title_Instrument2_Loop    ; Loop here.

    ; The indexes of the effect blocks used by this song.
sf_title_EffectBlockTable:
sf_title_DisarkPointerRegionStart7:
    dw sf_title_EffectBlock_P5P0P8    ; Index 0
    dw sf_title_EffectBlock_P5P1P8    ; Index 1
sf_title_DisarkPointerRegionEnd7:
sf_title_EffectBlock_P5P0P8:
    db 5
    db 0
    db 8

sf_title_EffectBlock_P5P1P8:
    db 5
    db 1
    db 8

sf_title_DisarkByteRegionEnd0:

    ; Subsong 0
    ; ----------------------
sf_title_Subsong0_DisarkByteRegionStart0:
sf_title_Subsong0_Start:
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 1    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 1    ; End index (>=0).
    db 6    ; Initial speed (>=0).
    db 19    ; Base note index (>=0).

sf_title_Subsong0_Linker:
sf_title_Subsong0_DisarkPointerRegionStart1:
    ; Position 0
sf_title_Subsong0_Linker_Loop:
    dw sf_title_Subsong0_Track0
    dw sf_title_Subsong0_Track1
    dw sf_title_Subsong0_Track2
    dw sf_title_Subsong0_LinkerBlock0
    ; Position 1
    dw sf_title_Subsong0_Track0
    dw sf_title_Subsong0_Track3
    dw sf_title_Subsong0_Track4
    dw sf_title_Subsong0_LinkerBlock0
sf_title_Subsong0_DisarkPointerRegionEnd1:
    dw 0    ; Loop.
sf_title_Subsong0_DisarkWordForceReference2:
    dw sf_title_Subsong0_Linker_Loop

sf_title_Subsong0_LinkerBlock0:
    db 32    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
sf_title_Subsong0_DisarkWordForceReference3:
    dw sf_title_Subsong0_SpeedTrack0    ; SpeedTrack address.
sf_title_Subsong0_DisarkWordForceReference4:
    dw sf_title_Subsong0_EventTrack0    ; EventTrack address.

sf_title_Subsong0_Track0:
    db 61
    db 127    ; Waits for 128 lines.

sf_title_Subsong0_Track1:
    db 237
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 50
    db 60    ; Waits for 1 line.

    db 48
    db 45
    db 41
    db 60    ; Waits for 1 line.

    db 46
    db 60    ; Waits for 1 line.

    db 50
    db 60    ; Waits for 1 line.

    db 53
    db 50
    db 46
    db 60    ; Waits for 1 line.

    db 45
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 53
    db 48
    db 45
    db 60    ; Waits for 1 line.

    db 43
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 52
    db 48
    db 43
    db 61
    db 127    ; Waits for 128 lines.

sf_title_Subsong0_Track2:
    db 206
    db 2    ; New Instrument (2).
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 14
    db 60    ; Waits for 1 line.

    db 21
    db 60    ; Waits for 1 line.

    db 14
    db 60    ; Waits for 1 line.

    db 10
    db 60    ; Waits for 1 line.

    db 10
    db 60    ; Waits for 1 line.

    db 17
    db 60    ; Waits for 1 line.

    db 10
    db 60    ; Waits for 1 line.

    db 17
    db 60    ; Waits for 1 line.

    db 17
    db 60    ; Waits for 1 line.

    db 24
    db 60    ; Waits for 1 line.

    db 17
    db 60    ; Waits for 1 line.

    db 12
    db 60    ; Waits for 1 line.

    db 12
    db 60    ; Waits for 1 line.

    db 19
    db 60    ; Waits for 1 line.

    db 12
    db 61
    db 127    ; Waits for 128 lines.

sf_title_Subsong0_Track3:
    db 242
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 48
    db 45
    db 48
    db 50
    db 60    ; Waits for 1 line.

    db 53
    db 60    ; Waits for 1 line.

    db 50
    db 48
    db 46
    db 48
    db 50
    db 60    ; Waits for 1 line.

    db 46
    db 60    ; Waits for 1 line.

    db 52
    db 50
    db 48
    db 50
    db 52
    db 60    ; Waits for 1 line.

    db 55
    db 60    ; Waits for 1 line.

    db 53
    db 52
    db 50
    db 48
    db 45
    db 60    ; Waits for 1 line.

    db 50
    db 61
    db 127    ; Waits for 128 lines.

sf_title_Subsong0_Track4:
    db 206
    db 2    ; New Instrument (2).
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 14
    db 60    ; Waits for 1 line.

    db 21
    db 60    ; Waits for 1 line.

    db 14
    db 60    ; Waits for 1 line.

    db 10
    db 60    ; Waits for 1 line.

    db 10
    db 60    ; Waits for 1 line.

    db 17
    db 60    ; Waits for 1 line.

    db 10
    db 60    ; Waits for 1 line.

    db 12
    db 60    ; Waits for 1 line.

    db 12
    db 60    ; Waits for 1 line.

    db 19
    db 60    ; Waits for 1 line.

    db 12
    db 60    ; Waits for 1 line.

    db 14
    db 60    ; Waits for 1 line.

    db 14
    db 60    ; Waits for 1 line.

    db 21
    db 60    ; Waits for 1 line.

    db 14
    db 61
    db 127    ; Waits for 128 lines.

    ; The speed tracks
sf_title_Subsong0_SpeedTrack0:
    db 255    ; Wait for 128 lines.

    ; The event tracks
sf_title_Subsong0_EventTrack0:
    db 255    ; Wait for 128 lines.

sf_title_Subsong0_DisarkByteRegionEnd0:
__aks_sf_title_end:
end asm

#endif
