' Generated by tmx2bas.py --name a_map tests/conformance/assets/level.tmx -o tests/conformance/assets/level.bas
' Source: tests/conformance/assets/level.tmx, layer 'floor', 4x2 tiles, 8 bytes
' Do not edit; regenerate with tools/build_assets.sh.

DIM a_map(7) AS UBYTE => { _
    $00, $01, $02, $00, $02, $00, $01, $02 _
}

CONST a_map_W AS UBYTE = 4
CONST a_map_H AS UBYTE = 2
