' Generated by img2cpc.py --mode 0 --name a_msk0 --masked --palette-file tests/conformance/assets/pens16.pal tests/conformance/assets/msk0.png -o tests/conformance/assets/msk0.bas
' Source: tests/conformance/assets/msk0.png, 8x4 pixels, mode 0
' 1 frame(s) of 4 bytes x 4 lines, masked, 32 bytes each
' Do not edit; regenerate with tools/build_assets.sh.

DIM a_msk0(31) AS UBYTE => { _
    $AA, $04, $AA, $10, $AA, $14, $AA, $01, $55, $88, $55, $A0, $55, $A8, $55, $82, _
    $AA, $14, $AA, $01, $AA, $05, $AA, $11, $55, $A8, $55, $82, $55, $8A, $55, $A2 _
}

CONST a_msk0_W AS UBYTE = 4

CONST a_msk0_H AS UBYTE = 4

CONST a_msk0_FRAMES AS UBYTE = 1

CONST a_msk0_SIZE AS UBYTE = 32

DIM a_msk0_pal(15) AS UBYTE => { _
    $00, $07, $0E, $15, $01, $08, $0F, $16, $02, $09, $10, $17, $03, $0A, $11, $18 _
}

CONST a_msk0_PENS AS UBYTE = 16
