' Generated by img2cpc.py --mode 1 --name a_msk1 --masked --palette 0,26,6,18 tests/conformance/assets/msk1.png -o tests/conformance/assets/msk1.bas
' Source: tests/conformance/assets/msk1.png, 8x4 pixels, mode 1
' 1 frame(s) of 2 bytes x 4 lines, masked, 16 bytes each
' Do not edit; regenerate with tools/build_assets.sh.

DIM a_msk1(15) AS UBYTE => { _
    $AA, $14, $AA, $45, $55, $8A, $55, $A2, $AA, $45, $AA, $51, $55, $A2, $55, $28 _
}

CONST a_msk1_W AS UBYTE = 2

CONST a_msk1_H AS UBYTE = 4

CONST a_msk1_FRAMES AS UBYTE = 1

CONST a_msk1_SIZE AS UBYTE = 16

DIM a_msk1_pal(3) AS UBYTE => { _
    $00, $1A, $06, $12 _
}

CONST a_msk1_PENS AS UBYTE = 4
