' Generated by img2cpc.py --mode 1 --name a_pic --tiles --dedupe tests/conformance/assets/pic1.png -o tests/conformance/assets/pic1.bas
' Source: tests/conformance/assets/pic1.png, 32x16 pixels, mode 1
' 3 tiles of 16 bytes
' Do not edit; regenerate with tools/build_assets.sh.

DIM a_pic(47) AS UBYTE => { _
    $53, $53, $A6, $A6, $5C, $5C, $A9, $A9, $53, $53, $A6, $A6, $5C, $5C, $A9, $A9, _
    $05, $05, $F5, $F5, $0A, $0A, $FA, $FA, $05, $05, $F5, $F5, $0A, $0A, $FA, $FA, _
    $56, $56, $A3, $A3, $59, $59, $AC, $AC, $56, $56, $A3, $A3, $59, $59, $AC, $AC _
}

CONST a_pic_COUNT AS UBYTE = 3

DIM a_pic_MAP(7) AS UBYTE => { _
    $00, $01, $02, $00, $02, $00, $01, $02 _
}

CONST a_pic_MAPW AS UBYTE = 4

CONST a_pic_MAPH AS UBYTE = 2

DIM a_pic_pal(3) AS UBYTE => { _
    $00, $1A, $06, $12 _
}

CONST a_pic_PENS AS UBYTE = 4
