' Generated by img2cpc.py --plus-palette --name plusbars tests/conformance/assets/plus_bars.png -o tests/conformance/assets/plus_bars.bas
' Source: tests/conformance/assets/plus_bars.png, 16x1 pixels, CPC Plus
' 16 pen colours, 32 bytes
' Do not edit; regenerate with tools/build_assets.sh.

DIM plusbars_pal(31) AS UBYTE => { _
    $0F, $03, $1E, $08, $2D, $0D, $3C, $02, $4B, $07, $5A, $0C, $69, $01, $78, $06, _
    $87, $0B, $96, $00, $A5, $05, $B4, $0A, $C3, $0F, $D2, $04, $E1, $09, $F0, $0E _
}
