' Generated by img2cpc.py --mode 0 --name a_spr0 --write-palette tests/conformance/assets/pens16.pal tests/conformance/assets/spr0.png -o tests/conformance/assets/spr0.bas
' Source: tests/conformance/assets/spr0.png, 16x4 pixels, mode 0
' 1 frame(s) of 8 bytes x 4 lines, 32 bytes each
' Do not edit; regenerate with tools/build_assets.sh.

DIM a_spr0(31) AS UBYTE => { _
    $40, $4C, $70, $7C, $43, $4F, $73, $7F, $98, $B4, $A9, $87, $9B, $B7, $AA, $84, _
    $7C, $43, $4F, $73, $7F, $40, $4C, $70, $87, $9B, $B7, $AA, $84, $98, $B4, $A9 _
}

CONST a_spr0_W AS UBYTE = 8

CONST a_spr0_H AS UBYTE = 4

CONST a_spr0_FRAMES AS UBYTE = 1

CONST a_spr0_SIZE AS UBYTE = 32

DIM a_spr0_pal(15) AS UBYTE => { _
    $00, $07, $0E, $15, $01, $08, $0F, $16, $02, $09, $10, $17, $03, $0A, $11, $18 _
}

CONST a_spr0_PENS AS UBYTE = 16
