' Generated by img2cpc.py --mode 1 --name a_spr1 --palette 0,26,6,18 tests/conformance/assets/spr1.png -o tests/conformance/assets/spr1.bas
' Source: tests/conformance/assets/spr1.png, 8x4 pixels, mode 1
' 1 frame(s) of 2 bytes x 4 lines, 8 bytes each
' Do not edit; regenerate with tools/build_assets.sh.

DIM a_spr1(7) AS UBYTE => { _
    $53, $53, $5C, $5C, $53, $53, $5C, $5C _
}

CONST a_spr1_W AS UBYTE = 2

CONST a_spr1_H AS UBYTE = 4

CONST a_spr1_FRAMES AS UBYTE = 1

CONST a_spr1_SIZE AS UBYTE = 8

DIM a_spr1_pal(3) AS UBYTE => { _
    $00, $1A, $06, $12 _
}

CONST a_spr1_PENS AS UBYTE = 4
