' soft123.bas -- Arkos AKG song, converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @soft123 to MusicInit(@soft123, subsong).

#ifndef __AKS_SOFT123__
#define __AKS_SOFT123__

asm
    jp __aks_soft123_end
end asm
soft123:
asm
    ; New song, AKG format, v1.0.

    ; Generated by Arkos Tracker 2.

soft123_Newsong_Start:
    db "AT20"
    dw soft123_Newsong_ArpeggioTable    ; The address of the Arpeggio table.
    dw soft123_Newsong_PitchTable    ; The address of the Pitch table.
    dw soft123_Newsong_InstrumentTable    ; The address of the Instrument table.
    dw soft123_Newsong_EffectBlockTable    ; The address of the Effect Block table.

    ; The addresses of each Subsong:
    dw soft123_Newsong_Subsong0_Start

    ; Declares all the Arpeggios.
soft123_Newsong_ArpeggioTable:

    ; Declares all the Pitches.
soft123_Newsong_PitchTable:

    ; Declares all the Instruments.
soft123_Newsong_InstrumentTable:
    dw soft123_Newsong_EmptyInstrument
    dw soft123_Newsong_Instrument1

soft123_Newsong_EmptyInstrument:
    db 0    ; The speed (>0, 0 for 256).
soft123_Newsong_EmptyInstrument_Loop:
    db 0 ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

soft123_Newsong_Instrument1:
    db 1    ; The speed (>0, 0 for 256).
    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.

    ; The indexes of the effect blocks used by this song.
soft123_Newsong_EffectBlockTable:

    ; Subsong 0
    ; ----------------------
soft123_Newsong_Subsong0_Start:
    db 2    ; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
    db 0    ; Digichannel (0-2).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 2    ; End index (>=0).
    db 6    ; Initial speed (>=0).
    db 17    ; Base note index (>=0).

soft123_Newsong_Subsong0_Linker:
    ; Position 0
soft123_Newsong_Subsong0_Linker_Loop:
    dw soft123_Newsong_Subsong0_Track0
    dw soft123_Newsong_Subsong0_Track1
    dw soft123_Newsong_Subsong0_Track1
    dw soft123_Newsong_Subsong0_LinkerBlock0

    ; Position 1
    dw soft123_Newsong_Subsong0_Track1
    dw soft123_Newsong_Subsong0_Track0
    dw soft123_Newsong_Subsong0_Track1
    dw soft123_Newsong_Subsong0_LinkerBlock0

    ; Position 2
    dw soft123_Newsong_Subsong0_Track1
    dw soft123_Newsong_Subsong0_Track1
    dw soft123_Newsong_Subsong0_Track0
    dw soft123_Newsong_Subsong0_LinkerBlock0

    dw 0    ; Loop.
    dw soft123_Newsong_Subsong0_Linker_Loop

soft123_Newsong_Subsong0_LinkerBlock0:
    db 48    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
    dw soft123_Newsong_Subsong0_SpeedTrack0    ; SpeedTrack address.
    dw soft123_Newsong_Subsong0_EventTrack0    ; EventTrack address.

soft123_Newsong_Subsong0_Track0:
    db 159
    db 1    ; New Instrument (1).
    db 61, 6    ; Waits for 7 lines.

    db 33
    db 61, 5    ; Waits for 6 lines.

    db 35
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 36
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 38
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 40
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 42
    db 60    ; Waits for 1 line.

    db 43
    db 45
    db 47
    db 48
    db 50
    db 52
    db 54
    db 55
    db 61, 127    ; Waits for 128 lines.

soft123_Newsong_Subsong0_Track1:
    db 61, 127    ; Waits for 128 lines.

    ; The speed tracks
soft123_Newsong_Subsong0_SpeedTrack0:
    db 255    ; Wait for 128 lines.

    ; The event tracks
soft123_Newsong_Subsong0_EventTrack0:
    db 255    ; Wait for 128 lines.
__aks_soft123_end:
end asm

#endif
