' softhard.bas -- Arkos AKG song, converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @softhard to MusicInit(@softhard, subsong).

#ifndef __AKS_SOFTHARD__
#define __AKS_SOFTHARD__

asm
    jp __aks_softhard_end
end asm
softhard:
asm
    ; New song, AKG format, v1.0.

    ; Generated by Arkos Tracker 2.

softhard_Newsong_Start:
softhard_Newsong_StartDisarkGenerateExternalLabel:

softhard_Newsong_DisarkByteRegionStart0:
    db "AT20"
softhard_Newsong_DisarkPointerRegionStart1:
    dw softhard_Newsong_ArpeggioTable    ; The address of the Arpeggio table.
    dw softhard_Newsong_PitchTable    ; The address of the Pitch table.
    dw softhard_Newsong_InstrumentTable    ; The address of the Instrument table.
    dw softhard_Newsong_EffectBlockTable    ; The address of the Effect Block table.
softhard_Newsong_DisarkPointerRegionEnd1:

    ; The addresses of each Subsong:
softhard_Newsong_DisarkPointerRegionStart2:
    dw softhard_Newsong_Subsong0_Start
softhard_Newsong_DisarkPointerRegionEnd2:

    ; Declares all the Arpeggios.
softhard_Newsong_ArpeggioTable:
softhard_Newsong_DisarkPointerRegionStart3:
softhard_Newsong_DisarkPointerRegionEnd3:

    ; Declares all the Pitches.
softhard_Newsong_PitchTable:
softhard_Newsong_DisarkPointerRegionStart4:
softhard_Newsong_DisarkPointerRegionEnd4:

    ; Declares all the Instruments.
softhard_Newsong_InstrumentTable:
softhard_Newsong_DisarkPointerRegionStart5:
    dw softhard_Newsong_EmptyInstrument
    dw softhard_Newsong_Instrument1
softhard_Newsong_DisarkPointerRegionEnd5:

softhard_Newsong_EmptyInstrument:
    db 0    ; The speed (>0, 0 for 256).
softhard_Newsong_EmptyInstrument_Loop:
    db 0 ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

softhard_Newsong_Instrument1:
    db 27    ; The speed (>0, 0 for 256).
softhard_Newsong_Instrument1_Loop:
    db 5 ; Soft and Hard. Envelope: 8. Retrig ? false. Noise ? false.
    db 72    ; Second byte. Simple Soft? trueSimple Hard? false.
    dw 1    ; Forced period.

    db 5    ; Soft and Hard. Envelope: 8. Retrig ? false. Noise ? false.
    db 66    ; Second byte. Simple Soft? falseSimple Hard? false.
    dw -39    ; Pitch.
    dw 1    ; Forced period.

    db 5    ; Soft and Hard. Envelope: 8. Retrig ? false. Noise ? false.
    db 66    ; Second byte. Simple Soft? falseSimple Hard? false.
    dw 32    ; Pitch.
    dw 2    ; Forced period.

    db 5    ; Soft and Hard. Envelope: 8. Retrig ? false. Noise ? false.
    db 65    ; Second byte. Simple Soft? falseSimple Hard? false.
    db 1    ; Arpeggio.
    dw 2    ; Forced period.

    db 5    ; Soft and Hard. Envelope: 8. Retrig ? false. Noise ? false.
    db 67    ; Second byte. Simple Soft? falseSimple Hard? false.
    db 2    ; Arpeggio.
    dw -2    ; Pitch.
    dw 3    ; Forced period.

    db 5    ; Soft and Hard. Envelope: 8. Retrig ? false. Noise ? false.
    db 67    ; Second byte. Simple Soft? falseSimple Hard? false.
    db -5    ; Arpeggio.
    dw 3    ; Pitch.
    dw 3    ; Forced period.

    db 7    ; Loop.
softhard_Newsong_DisarkWordForceReference6:
    dw softhard_Newsong_Instrument1_Loop    ; Loop here.

    ; The indexes of the effect blocks used by this song.
softhard_Newsong_EffectBlockTable:

softhard_Newsong_DisarkByteRegionEnd0:

    ; Subsong 0
    ; ----------------------
softhard_Newsong_Subsong0_DisarkByteRegionStart0:
softhard_Newsong_Subsong0_Start:
    db 2    ; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
    db 0    ; Digichannel (0-2).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 0    ; End index (>=0).
    db 6    ; Initial speed (>=0).
    db 0    ; Base note index (>=0).

softhard_Newsong_Subsong0_Linker:
softhard_Newsong_Subsong0_DisarkPointerRegionStart1:
    ; Position 0
softhard_Newsong_Subsong0_Linker_Loop:
    dw softhard_Newsong_Subsong0_Track0
    dw softhard_Newsong_Subsong0_Track1
    dw softhard_Newsong_Subsong0_Track1
    dw softhard_Newsong_Subsong0_LinkerBlock0

softhard_Newsong_Subsong0_DisarkPointerRegionEnd1:
    dw 0    ; Loop.
softhard_Newsong_Subsong0_DisarkWordForceReference2:
    dw softhard_Newsong_Subsong0_Linker_Loop

softhard_Newsong_Subsong0_LinkerBlock0:
    db 64    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
softhard_Newsong_Subsong0_DisarkWordForceReference3:
    dw softhard_Newsong_Subsong0_SpeedTrack0    ; SpeedTrack address.
softhard_Newsong_Subsong0_DisarkWordForceReference4:
    dw softhard_Newsong_Subsong0_EventTrack0    ; EventTrack address.

softhard_Newsong_Subsong0_Track0:
    db 176
    db 1    ; New Instrument (1).
    db 61, 127    ; Waits for 128 lines.

softhard_Newsong_Subsong0_Track1:
    db 61, 127    ; Waits for 128 lines.

    ; The speed tracks
softhard_Newsong_Subsong0_SpeedTrack0:
    db 255    ; Wait for 128 lines.

    ; The event tracks
softhard_Newsong_Subsong0_EventTrack0:
    db 255    ; Wait for 128 lines.

softhard_Newsong_Subsong0_DisarkByteRegionEnd0:
__aks_softhard_end:
end asm

#endif
