#!/bin/sh
# Regenerate lib/music/akg_cpc.asm from the Arkos Tracker 3.7 AKG player:
#
#   Rasm 3.3    assembles PlayerAkg.asm for the CPC, sound effects on,
#               default (full) player configuration, at ORG 0x8000 (symbols
#               to a file)
#   Disark      binary + symbols -> plain Z80 source (pasmo profile, 0x hex,
#               undocumented opcodes as bytes)
#   postprocess.py   -> zxbasm syntax (labels with ':' ...)
#
# Then the key check: the converted source, assembled by zxbasm at the same
# ORG (and at a second ORG, to prove it relocates), must be byte-identical to
# what Rasm produced.
#
# Run tools/arkos/fetch.sh first. Needs zxbasm: the zxbasic checkout
# (../zxbasic, or $ZXBASIC) with poetry, or `zxbasm` on PATH.
#
# NOTE: the Arkos tools (Rasm, Disark) can hang inside some sandboxes; run
# this outside one if it does.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../.." && pwd)
W=$HERE/work
B=$W/bin
OUT=$REPO/lib/music/akg_cpc.asm
SRC=$W/at3/players/playerAkg/sources/z80
ZXBASIC=${ZXBASIC:-$REPO/../zxbasic}
[ -x "$B/rasm" ] && [ -x "$B/disark" ] || { echo "run fetch.sh first" >&2; exit 1; }

if command -v zxbasm >/dev/null 2>&1; then ZXBASM="zxbasm"; else ZXBASM="poetry run zxbasm"; fi
zxbasm() { (cd "$ZXBASIC" && $ZXBASM "$@"); }

BUILD=$W/build; rm -rf "$BUILD"; mkdir -p "$BUILD"; cd "$BUILD"

assemble_rasm() { # org outbin symfile
cat > wrap_$1.asm <<EOT
 org $1
PLY_AKG_HARDWARE_CPC = 1
PLY_AKG_MANAGE_SOUND_EFFECTS = 1
Player:
 include "$SRC/PlayerAkg.asm"
PlayerEnd:
EOT
  "$B/rasm" wrap_$1.asm -ob "$2" ${3:+-s -sl -sq -os "$3"} >rasm_$1.log 2>&1 || { cat rasm_$1.log; exit 1; }
}

assemble_rasm "#8000" ref.bin ref.sym
"$B/disark" ref.bin ref.dk.asm --symbolFile ref.sym --sourceProfile pasmo \
  --hexPrefix 0x --undocumentedOpcodesToBytes --loadAddress 0x8000 --genOrg
python3 "$HERE/postprocess.py" ref.dk.asm body.asm \
  --case-from "$SRC/PlayerAkg.asm" --case-from "$SRC/PlayerAkg_SoundEffects.asm" \
  --drop-label PLAYER --drop-label PLAYEREND

{
cat <<'EOT'
; Arkos Tracker 3.7 AKG player, Amstrad CPC, sound effects enabled, full
; (default) player configuration so any song/effects bank works.
;
; GENERATED by tools/arkos/convert.sh (Rasm 3.3 -> Disark 2.0.0 ->
; postprocess.py) from players/playerAkg/sources/z80/PlayerAkg.asm of the
; Arkos Tracker 3.7 release. Do not edit. Relocatable (all references are
; labels). Copyright (c) 2016-2025 Julien Nevo, MIT licence: see
; LICENSE.arkos.
;
; Entry points (labels): PLY_AKG_Init (HL = song, A = subsong),
; PLY_AKG_Play, PLY_AKG_Stop, PLY_AKG_InitSoundEffects (HL = effects),
; PLY_AKG_PlaySoundEffect (A = effect >0, C = channel 0-2, B = inverted
; volume 0-16), PLY_AKG_StopSoundEffectFromChannel (A = channel).
; The player uses the stack for speed: interrupts must be off while it
; runs, and it clobbers every register including IX, IY and the alternates.
;
EOT
cat body.asm
} > akg_cpc.asm

# --- the key check: zxbasm output == Rasm output -------------------------
check() { # org (hex digits)
  assemble_rasm "#$1" ref_$1.bin
  { echo "org 0x$1"; cat akg_cpc.asm; } > chk_$1.asm
  zxbasm "$BUILD/chk_$1.asm" -o "$BUILD/chk_$1.bin"
  if cmp -s ref_$1.bin chk_$1.bin; then
    echo "byte-identical at ORG 0x$1 ($(wc -c < chk_$1.bin | tr -d ' ') bytes)"
  else
    echo "MISMATCH at ORG 0x$1" >&2; cmp ref_$1.bin chk_$1.bin | head -3 >&2; exit 1
  fi
}
check 8000
check 1234
check 4000

cp akg_cpc.asm "$OUT"
echo "wrote $OUT"
