#!/bin/sh
# Regenerate lib/music/akg_cpc.asm (Amstrad CPC) and lib/music/akg_zx.asm
# (ZX Spectrum 128K: AY at ports &FFFD/&BFFD, 1.7734 MHz period table) from
# the Arkos Tracker 3.7 AKG player:
#
#   Rasm 3.3    assembles PlayerAkg.asm for the CPC / the Spectrum, effects on,
#               default (full) player configuration, at ORG 0x8000 (symbols
#               to a file)
#   Disark      binary + symbols -> plain Z80 source (pasmo profile, 0x hex,
#               undocumented opcodes as bytes)
#   postprocess.py   -> zxbasm syntax (labels with ':' ...)
#
# Then the key check: the converted source, assembled by zxbasm at the same
# ORG (and at a second ORG, to prove it relocates), must be byte-identical to
# what Rasm produced.
#
# Run tools/arkos/fetch.sh first. Needs zxbasm: the zxbasic checkout
# (../zxbasic, or $ZXBASIC) with poetry, or `zxbasm` on PATH.
#
# NOTE: the Arkos tools (Rasm, Disark) can hang inside some sandboxes; run
# this outside one if it does.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../.." && pwd)
W=$HERE/work
B=$W/bin
SRC=$W/at3/players/playerAkg/sources/z80
ZXBASIC=${ZXBASIC:-$REPO/../zxbasic}
[ -x "$B/rasm" ] && [ -x "$B/disark" ] || { echo "run fetch.sh first" >&2; exit 1; }

if command -v zxbasm >/dev/null 2>&1; then ZXBASM="zxbasm"; else ZXBASM="poetry run zxbasm"; fi
zxbasm() { (cd "$ZXBASIC" && $ZXBASM "$@"); }

BUILD=$W/build; rm -rf "$BUILD"; mkdir -p "$BUILD"; cd "$BUILD"

assemble_rasm() { # hw org outbin symfile
cat > wrap_$1_$2.asm <<EOT
 org $2
PLY_AKG_HARDWARE_$1 = 1
PLY_AKG_MANAGE_SOUND_EFFECTS = 1
Player:
 include "$SRC/PlayerAkg.asm"
PlayerEnd:
EOT
  "$B/rasm" wrap_$1_$2.asm -ob "$3" ${4:+-s -sl -sq -os "$4"} >rasm_$1_$2.log 2>&1 || { cat rasm_$1_$2.log; exit 1; }
}

convert() { # HW(CPC|SPECTRUM) name description
  hw=$1; name=$2; desc=$3
  OUT=$REPO/lib/music/akg_$name.asm
  assemble_rasm $hw "#8000" ref_$name.bin ref_$name.sym
  "$B/disark" ref_$name.bin ref_$name.dk.asm --symbolFile ref_$name.sym --sourceProfile pasmo \
    --hexPrefix 0x --undocumentedOpcodesToBytes --loadAddress 0x8000 --genOrg
  python3 "$HERE/postprocess.py" ref_$name.dk.asm body_$name.asm \
    --case-from "$SRC/PlayerAkg.asm" --case-from "$SRC/PlayerAkg_SoundEffects.asm" \
    --drop-label PLAYER --drop-label PLAYEREND

  {
  cat <<EOT
; Arkos Tracker 3.7 AKG player, $desc, sound effects enabled, full
; (default) player configuration so any song/effects bank works.
;
; GENERATED by tools/arkos/convert.sh (Rasm 3.3 -> Disark 2.0.0 ->
; postprocess.py) from players/playerAkg/sources/z80/PlayerAkg.asm of the
; Arkos Tracker 3.7 release. Do not edit. Relocatable (all references are
; labels). Copyright (c) 2016-2025 Julien Nevo, MIT licence: see
; LICENSE.arkos.
;
; Entry points (labels): PLY_AKG_Init (HL = song, A = subsong),
; PLY_AKG_Play, PLY_AKG_Stop, PLY_AKG_InitSoundEffects (HL = effects),
; PLY_AKG_PlaySoundEffect (A = effect >0, C = channel 0-2, B = inverted
; volume 0-16), PLY_AKG_StopSoundEffectFromChannel (A = channel).
; The player uses the stack for speed: interrupts must be off while it
; runs, and it clobbers every register including IX, IY and the alternates.
;
EOT
  cat body_$name.asm
  } > akg_$name.asm

  # --- the key check: zxbasm output == Rasm output -----------------------
  for o in 8000 1234 4000; do
    assemble_rasm $hw "#$o" ref_${name}_$o.bin
    { echo "org 0x$o"; cat akg_$name.asm; } > chk_${name}_$o.asm
    zxbasm "$BUILD/chk_${name}_$o.asm" -o "$BUILD/chk_${name}_$o.bin"
    if cmp -s ref_${name}_$o.bin chk_${name}_$o.bin; then
      echo "$name: byte-identical at ORG 0x$o ($(wc -c < chk_${name}_$o.bin | tr -d ' ') bytes)"
    else
      echo "$name: MISMATCH at ORG 0x$o" >&2; cmp ref_${name}_$o.bin chk_${name}_$o.bin | head -3 >&2; exit 1
    fi
  done
  cp akg_$name.asm "$OUT"
  echo "wrote $OUT"
}

convert CPC cpc "Amstrad CPC"
convert SPECTRUM zx "ZX Spectrum 128K (AY, ports &FFFD/&BFFD, 1773400 Hz)"
