; Arkos Tracker 3.7 AKG player, Amstrad CPC, sound effects enabled, full
; (default) player configuration so any song/effects bank works.
;
; GENERATED by tools/arkos/convert.sh (Rasm 3.3 -> Disark 2.0.0 ->
; postprocess.py) from players/playerAkg/sources/z80/PlayerAkg.asm of the
; Arkos Tracker 3.7 release. Do not edit. Relocatable (all references are
; labels). Copyright (c) 2016-2025 Julien Nevo, MIT licence: see
; LICENSE.arkos.
;
; Entry points (labels): PLY_AKG_Init (HL = song, A = subsong),
; PLY_AKG_Play, PLY_AKG_Stop, PLY_AKG_InitSoundEffects (HL = effects),
; PLY_AKG_PlaySoundEffect (A = effect >0, C = channel 0-2, B = inverted
; volume 0-16), PLY_AKG_StopSoundEffectFromChannel (A = channel).
; The player uses the stack for speed: interrupts must be off while it
; runs, and it clobbers every register including IX, IY and the alternates.
;
PLY_AKG_Start:
    jp PLY_AKG_Init
    jp PLY_AKG_Play
    jp PLY_AKG_InitTableOrA_End
PLY_AKG_InitSoundEffects:
    ld (PLY_AKG_PtSoundEffectTable+1),hl
    ret
PLY_AKG_PlaySoundEffect:
    dec a
PLY_AKG_PtSoundEffectTable:
    ld hl,0
    ld e,a
    ld d,0
    add hl,de
    add hl,de
    ld e,(hl)
    inc hl
    ld d,(hl)
    ld a,(de)
    inc de
    ex af,af'
    ld a,b
    ld hl,PLY_AKG_Channel1_SoundEffectData
    ld b,0
    sla c
    sla c
    sla c
    add hl,bc
    ld (hl),e
    inc hl
    ld (hl),d
    inc hl
    ld (hl),a
    inc hl
    ld (hl),0
    inc hl
    ex af,af'
    ld (hl),a
    ret
PLY_AKG_StopSoundEffectFromChannel:
    add a,a
    add a,a
    add a,a
    ld e,a
    ld d,0
    ld hl,PLY_AKG_Channel1_SoundEffectData
    add hl,de
    ld (hl),d
    inc hl
    ld (hl),d
    ret
PLY_AKG_PlaySoundEffectsStream:
    rla
    rla
    ld ix,PLY_AKG_Channel1_SoundEffectData
    ld iy,PLY_AKG_PSGReg8
    ld hl,PLY_AKG_PSGReg01_Instr+1
    exx
    ld c,a
    call PLY_AKG_PSES_Play
    ld ix,PLY_AKG_Channel2_SoundEffectData
    ld iy,PLY_AKG_PSGReg9
    exx
    ld hl,PLY_AKG_PSGReg23_Instr+1
    exx
    srl c
    call PLY_AKG_PSES_Play
    ld ix,PLY_AKG_Channel3_SoundEffectData
    ld iy,PLY_AKG_PSGReg10
    exx
    ld hl,PLY_AKG_PSGReg45_Instr+1
    exx
    rr c
    call PLY_AKG_PSES_Play
    ld a,c
    ret
PLY_AKG_PSES_Play:
    ld l,(ix+0)
    ld h,(ix+1)
    ld a,l
    or h
    ret z
PLY_AKG_PSES_ReadFirstByte:
    ld a,(hl)
    inc hl
    ld b,a
    rra
    jr c,PLY_AKG_PSES_SoftwareOrSoftwareAndHardware
    rra
    jr c,PLY_AKG_PSES_HardwareOnly
    rra
    jr c,PLY_AKG_PSES_S_EndOrLoop
    call PLY_AKG_PSES_ManageVolumeFromA_Filter4Bits
    rl b
    call PLY_AKG_PSES_ReadNoiseIfNeededAndOpenOrCloseNoiseChannel
    set 2,c
    jr PLY_AKG_PSES_SavePointerAndExit
PLY_AKG_PSES_S_EndOrLoop:
    rra
    jr c,PLY_AKG_PSES_S_Loop
    xor a
    ld (ix+0),a
    ld (ix+1),a
    ret
PLY_AKG_PSES_S_Loop:
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    jr PLY_AKG_PSES_ReadFirstByte
PLY_AKG_PSES_SavePointerAndExit:
    ld a,(ix+3)
    cp (ix+4)
    jr c,PLY_AKG_PSES_NotReached
    ld (ix+3),0
    db 221
    db 117
    db 0
    db 221
    db 116
    db 1
    ret
PLY_AKG_PSES_NotReached:
    inc (ix+3)
    ret
PLY_AKG_PSES_HardwareOnly:
    call PLY_AKG_PSES_Shared_ReadRetrigHardwareEnvPeriodNoise
    set 2,c
    jr PLY_AKG_PSES_SavePointerAndExit
PLY_AKG_PSES_SoftwareOrSoftwareAndHardware:
    rra
    jr c,PLY_AKG_PSES_SoftwareAndHardware
    call PLY_AKG_PSES_ManageVolumeFromA_Filter4Bits
    rl b
    call PLY_AKG_PSES_ReadNoiseIfNeededAndOpenOrCloseNoiseChannel
    res 2,c
    call PLY_AKG_PSES_ReadSoftwarePeriod
    jr PLY_AKG_PSES_SavePointerAndExit
PLY_AKG_PSES_SoftwareAndHardware:
    call PLY_AKG_PSES_Shared_ReadRetrigHardwareEnvPeriodNoise
    call PLY_AKG_PSES_ReadSoftwarePeriod
    res 2,c
    jr PLY_AKG_PSES_SavePointerAndExit
PLY_AKG_PSES_Shared_ReadRetrigHardwareEnvPeriodNoise:
    rra
    jr nc,PLY_AKG_PSES_H_AfterRetrig
    ld d,a
    ld a,255
    ld (PLY_AKG_PSGReg13_OldValue+1),a
    ld a,d
PLY_AKG_PSES_H_AfterRetrig:
    and 7
    add a,8
    ld (PLY_AKG_PSGReg13_Instr+1),a
    rl b
    call PLY_AKG_PSES_ReadNoiseIfNeededAndOpenOrCloseNoiseChannel
    call PLY_AKG_PSES_ReadHardwarePeriod
    ld a,16
    jp PLY_AKG_PSES_ManageVolumeFromA_Hard
PLY_AKG_PSES_ReadNoiseIfNeededAndOpenOrCloseNoiseChannel:
    jr c,PLY_AKG_PSES_ReadNoiseAndOpenNoiseChannel_OpenNoise
    set 5,c
    ret
PLY_AKG_PSES_ReadNoiseAndOpenNoiseChannel_OpenNoise:
    ld a,(hl)
    ld (PLY_AKG_PSGReg6),a
    inc hl
    res 5,c
    ret
PLY_AKG_PSES_ReadHardwarePeriod:
    ld a,(hl)
    ld (PLY_AKG_PSGHardwarePeriod_Instr+1),a
    inc hl
    ld a,(hl)
    ld (PLY_AKG_PSGHardwarePeriod_Instr+2),a
    inc hl
    ret
PLY_AKG_PSES_ReadSoftwarePeriod:
    ld a,(hl)
    inc hl
    exx
    ld (hl),a
    inc hl
    exx
    ld a,(hl)
    inc hl
    exx
    ld (hl),a
    exx
    ret
PLY_AKG_PSES_ManageVolumeFromA_Filter4Bits:
    and 15
PLY_AKG_PSES_ManageVolumeFromA_Hard:
    sub (ix+2)
    jr nc,PLY_AKG_PSES_MVFA_NoOverflow
    xor a
PLY_AKG_PSES_MVFA_NoOverflow:
    ld (iy+0),a
    ret
PLY_AKG_Channel1_SoundEffectData:
    dw 0
PLY_AKG_Channel1_SoundEffectInvertedVolume:
    db 0
PLY_AKG_Channel1_SoundEffectCurrentStep:
    db 0
PLY_AKG_Channel1_SoundEffectSpeed:
    db 0
    db 0
    db 0
    db 0
PLY_AKG_Channel2_SoundEffectData:
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
PLY_AKG_Channel3_SoundEffectData:
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
    db 0
PLY_AKG_Init:
    ld de,4
    add hl,de
    ld de,PLY_AKG_ArpeggiosTable+1
    ldi
    ldi
    ld de,PLY_AKG_PitchesTable+1
    ldi
    ldi
    ld de,PLY_AKG_InstrumentsTable+1
    ldi
    ldi
    ld c,(hl)
    inc hl
    ld b,(hl)
    inc hl
    ld (PLY_AKG_Channel_ReadEffects_EffectBlocks1+1),bc
    ld (PLY_AKG_Channel_ReadEffects_EffectBlocks2+1),bc
    add a,a
    ld e,a
    ld d,0
    add hl,de
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld de,5
    add hl,de
    ld de,PLY_AKG_CHANNEL3_READCELLEND+1
    ldi
    ld de,PLY_AKG_CHANNEL1_NOTE+1
    ldi
    ld (PLY_AKG_ReadLinker+1),hl
    ld hl,PLY_AKG_InitTable0
    ld bc,3584
    call PLY_AKG_Init_ReadWordsAndFill
    inc c
    ld hl,PLY_AKG_InitTable0_End
    ld b,3
    call PLY_AKG_Init_ReadWordsAndFill
    ld hl,PLY_AKG_InitTable1_End
    ld bc,3511
    call PLY_AKG_Init_ReadWordsAndFill
    ld a,255
    ld (PLY_AKG_PSGReg13_OldValue+1),a
    ld hl,(PLY_AKG_InstrumentsTable+1)
    ld e,(hl)
    inc hl
    ld d,(hl)
    ex de,hl
    inc hl
    ld (PLY_AKG_EndWithoutLoop+1),hl
    ld (PLY_AKG_Channel1_PtInstrument+1),hl
    ld (PLY_AKG_Channel2_PtInstrument+1),hl
    ld (PLY_AKG_Channel3_PtInstrument+1),hl
    ld hl,0
    ld (PLY_AKG_Channel1_SoundEffectData),hl
    ld (PLY_AKG_Channel2_SoundEffectData),hl
    ld (PLY_AKG_Channel3_SoundEffectData),hl
    ret
PLY_AKG_Init_ReadWordsAndFill_Loop:
    ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl
    ld a,c
    ld (de),a
PLY_AKG_Init_ReadWordsAndFill:
    djnz PLY_AKG_Init_ReadWordsAndFill_Loop
    ret
PLY_AKG_InitTable0:
    dw PLY_AKG_Channel1_InvertedVolumeIntegerAndDecimal+1
    dw PLY_AKG_Channel1_InvertedVolumeInteger
    dw PLY_AKG_Channel2_InvertedVolumeIntegerAndDecimal+1
    dw PLY_AKG_CHANNEL2_INVERTEDVOLUMEINTEGER
    dw PLY_AKG_Channel3_InvertedVolumeIntegerAndDecimal+1
    dw PLY_AKG_CHANNEL3_INVERTEDVOLUMEINTEGER
    dw PLY_AKG_CHANNEL1_PITCHTABLE_END+1
    dw PLY_AKG_CHANNEL1_PITCHTABLE_END+2
    dw PLY_AKG_CHANNEL2_PITCHTABLE_END+1
    dw PLY_AKG_CHANNEL2_PITCHTABLE_END+2
    dw PLY_AKG_CHANNEL3_PITCHTABLE_END+1
    dw PLY_AKG_CHANNEL3_PITCHTABLE_END+2
    dw PLY_AKG_Retrig+1
PLY_AKG_InitTable0_End:
PLY_AKG_InitTable1:
    dw PLY_AKG_PatternDecreasingHeight+1
    dw PLY_AKG_TickDecreasingCounter+1
PLY_AKG_InitTable1_End:
PLY_AKG_InitTableOrA:
    dw PLY_AKG_Channel1_IsVolumeSlide
    dw PLY_AKG_Channel2_IsVolumeSlide
    dw PLY_AKG_Channel3_IsVolumeSlide
    dw PLY_AKG_Channel1_IsArpeggioTable
    dw PLY_AKG_Channel2_IsArpeggioTable
    dw PLY_AKG_Channel3_IsArpeggioTable
    dw PLY_AKG_Channel1_IsPitchTable
    dw PLY_AKG_Channel2_IsPitchTable
    dw PLY_AKG_Channel3_IsPitchTable
    dw PLY_AKG_Channel1_IsPitch
    dw PLY_AKG_Channel2_IsPitch
    dw PLY_AKG_Channel3_IsPitch
PLY_AKG_InitTableOrA_End:
PLY_AKG_Stop:
    ld (PLY_AKG_PSGReg13_End+1),sp
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_PSGReg8),a
    ld (PLY_AKG_PSGReg9),hl
    ld a,63
    jp PLY_AKG_SendPSGRegisters
PLY_AKG_Play:
    ld (PLY_AKG_PSGReg13_End+1),sp
    xor a
    ld (PLY_AKG_Event),a
PLY_AKG_TickDecreasingCounter:
    ld a,1
    dec a
    jp nz,PLY_AKG_SetSpeedBeforePlayStreams
PLY_AKG_PatternDecreasingHeight:
    ld a,1
    dec a
    jr nz,PLY_AKG_SetCurrentLineBeforeReadLine
PLY_AKG_ReadLinker:
PLY_AKG_ReadLinker_PtLinker:
    ld sp,0
    pop hl
    ld a,l
    or h
    jr nz,PLY_AKG_ReadLinker_NoLoop
    pop hl
    ld sp,hl
    pop hl
PLY_AKG_ReadLinker_NoLoop:
    ld (PLY_AKG_CHANNEL1_READTRACK+1),hl
    pop hl
    ld (PLY_AKG_CHANNEL2_READTRACK+1),hl
    pop hl
    ld (PLY_AKG_CHANNEL3_READTRACK+1),hl
    pop hl
    ld (PLY_AKG_ReadLinker+1),sp
    ld sp,hl
    pop hl
    ld c,l
    ld a,h
    ld (PLY_AKG_CHANNEL1_AFTERNOTEKNOWN+1),a
    pop hl
    ld a,l
    ld (PLY_AKG_CHANNEL2_AFTERNOTEKNOWN+1),a
    ld a,h
    ld (PLY_AKG_CHANNEL3_AFTERNOTEKNOWN+1),a
    pop hl
    ld (PLY_AKG_SpeedTrack_PtTrack+1),hl
    pop hl
    ld (PLY_AKG_EventTrack_PtTrack+1),hl
    xor a
    ld (PLY_AKG_ReadLine+1),a
    ld (PLY_AKG_SpeedTrack_End+1),a
    ld (PLY_AKG_EventTrack_End+1),a
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    ld a,c
PLY_AKG_SetCurrentLineBeforeReadLine:
    ld (PLY_AKG_PatternDecreasingHeight+1),a
PLY_AKG_ReadLine:
PLY_AKG_SpeedTrack_WaitCounter:
    ld a,0
    sub 1
    jr nc,PLY_AKG_SpeedTrack_MustWait
PLY_AKG_SpeedTrack_PtTrack:
    ld hl,0
    ld a,(hl)
    inc hl
    srl a
    jr c,PLY_AKG_SpeedTrack_StorePointerAndWaitCounter
    jr nz,PLY_AKG_SpeedTrack_NormalValue
    ld a,(hl)
    inc hl
PLY_AKG_SpeedTrack_NormalValue:
    ld (PLY_AKG_CHANNEL3_READCELLEND+1),a
    xor a
PLY_AKG_SpeedTrack_StorePointerAndWaitCounter:
    ld (PLY_AKG_SpeedTrack_PtTrack+1),hl
PLY_AKG_SpeedTrack_MustWait:
    ld (PLY_AKG_ReadLine+1),a
PLY_AKG_SpeedTrack_End:
PLY_AKG_EventTrack_WaitCounter:
    ld a,0
    sub 1
    jr nc,PLY_AKG_EventTrack_MustWait
PLY_AKG_EventTrack_PtTrack:
    ld hl,0
    ld a,(hl)
    inc hl
    srl a
    jr c,PLY_AKG_EventTrack_StorePointerAndWaitCounter
    jr nz,PLY_AKG_EventTrack_NormalValue
    ld a,(hl)
    inc hl
PLY_AKG_EventTrack_NormalValue:
    ld (PLY_AKG_Event),a
    xor a
PLY_AKG_EventTrack_StorePointerAndWaitCounter:
    ld (PLY_AKG_EventTrack_PtTrack+1),hl
PLY_AKG_EventTrack_MustWait:
    ld (PLY_AKG_SpeedTrack_End+1),a
PLY_AKG_EventTrack_End:
PLY_AKG_Channel1_WaitCounter:
    ld a,0
    sub 1
    jr c,PLY_AKG_CHANNEL1_READTRACK
    ld (PLY_AKG_EventTrack_End+1),a
    jp PLY_AKG_CHANNEL1_READCELLEND
PLY_AKG_CHANNEL1_READTRACK:
PLY_AKG_Channel1_PtTrack:
    ld hl,0
    ld c,(hl)
    inc hl
    ld a,c
    and 63
    cp 60
    jr c,PLY_AKG_CHANNEL1_NOTE
    sub 60
    jp z,PLY_AKG_CHANNEL1_MAYBEEFFECTS
    dec a
    jr z,PLY_AKG_CHANNEL1_WAIT
    dec a
    jr z,PLY_AKG_CHANNEL1_SMALLWAIT
    ld a,(hl)
    inc hl
    jr PLY_AKG_CHANNEL1_AFTERNOTEKNOWN
PLY_AKG_CHANNEL1_SMALLWAIT:
    ld a,c
    rlca
    rlca
    and 3
    inc a
    ld (PLY_AKG_EventTrack_End+1),a
    jr PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL1_WAIT:
    ld a,(hl)
    ld (PLY_AKG_EventTrack_End+1),a
    inc hl
    jr PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL1_SAMEINSTRUMENT:
PLY_AKG_CHANNEL1_PTBASEINSTRUMENT:
    ld de,0
    ld (PLY_AKG_Channel1_PtInstrument+1),de
    jr PLY_AKG_CHANNEL1_AFTERINSTRUMENT
PLY_AKG_CHANNEL1_NOTE:
PLY_AKG_BaseNoteIndex:
    add a,0
PLY_AKG_CHANNEL1_AFTERNOTEKNOWN:
PLY_AKG_Channel1_Transposition:
    add a,0
    ld (PLY_AKG_Channel1_TrackNote+1),a
    rl c
    jr nc,PLY_AKG_CHANNEL1_SAMEINSTRUMENT
    ld a,(hl)
    inc hl
    exx
    ld l,a
    ld h,0
    add hl,hl
PLY_AKG_InstrumentsTable:
    ld de,0
    add hl,de
    ld sp,hl
    pop hl
    ld a,(hl)
    inc hl
    ld (PLY_AKG_CHANNEL1_INSTRUMENTORIGINALSPEED+1),a
    ld (PLY_AKG_Channel1_PtInstrument+1),hl
    ld (PLY_AKG_CHANNEL1_SAMEINSTRUMENT+1),hl
    exx
PLY_AKG_CHANNEL1_AFTERINSTRUMENT:
    ex de,hl
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_CHANNEL1_PITCHTABLE_END+1),hl
    ld (PLY_AKG_Channel1_ArpeggioTableCurrentStep+1),a
    ld (PLY_AKG_Channel1_PitchTableCurrentStep+1),a
    ld (PLY_AKG_CHANNEL1_INSTRUMENTSTEP+2),a
PLY_AKG_CHANNEL1_INSTRUMENTORIGINALSPEED:
    ld a,0
    ld (PLY_AKG_Channel1_InstrumentSpeed+1),a
    ld a,183
    ld (PLY_AKG_Channel1_IsPitch),a
    ld a,(PLY_AKG_Channel1_ArpeggioBaseSpeed)
    ld (PLY_AKG_Channel1_ArpeggioTableSpeed),a
    ld a,(PLY_AKG_Channel1_PitchBaseSpeed)
    ld (PLY_AKG_Channel1_PitchTableSpeed),a
    ld hl,(PLY_AKG_Channel1_ArpeggioTableBase)
    ld (PLY_AKG_Channel1_ArpeggioTable+1),hl
    ld hl,(PLY_AKG_Channel1_PitchTableBase)
    ld (PLY_AKG_Channel1_PitchTable+1),hl
    ex de,hl
    rl c
    jp c,PLY_AKG_CHANNEL1_READEFFECTS
PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER:
    ld (PLY_AKG_CHANNEL1_READTRACK+1),hl
PLY_AKG_CHANNEL1_READCELLEND:
PLY_AKG_Channel2_WaitCounter:
    ld a,0
    sub 1
    jr c,PLY_AKG_CHANNEL2_READTRACK
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    jp PLY_AKG_CHANNEL2_READCELLEND
PLY_AKG_CHANNEL2_READTRACK:
PLY_AKG_Channel2_PtTrack:
    ld hl,0
    ld c,(hl)
    inc hl
    ld a,c
    and 63
    cp 60
    jr c,PLY_AKG_CHANNEL2_NOTE
    sub 60
    jp z,PLY_AKG_CHANNEL1_READEFFECTSEND
    dec a
    jr z,PLY_AKG_CHANNEL2_WAIT
    dec a
    jr z,PLY_AKG_CHANNEL2_SMALLWAIT
    ld a,(hl)
    inc hl
    jr PLY_AKG_CHANNEL2_AFTERNOTEKNOWN
PLY_AKG_CHANNEL2_SMALLWAIT:
    ld a,c
    rlca
    rlca
    and 3
    inc a
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    jr PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL2_WAIT:
    ld a,(hl)
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    inc hl
    jr PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL2_SAMEINSTRUMENT:
PLY_AKG_CHANNEL2_PTBASEINSTRUMENT:
    ld de,0
    ld (PLY_AKG_Channel2_PtInstrument+1),de
    jr PLY_AKG_CHANNEL2_AFTERINSTRUMENT
PLY_AKG_CHANNEL2_NOTE:
    ld b,a
    ld a,(PLY_AKG_CHANNEL1_NOTE+1)
    add a,b
PLY_AKG_CHANNEL2_AFTERNOTEKNOWN:
PLY_AKG_Channel2_Transposition:
    add a,0
    ld (PLY_AKG_CHANNEL2_TRACKNOTE+1),a
    rl c
    jr nc,PLY_AKG_CHANNEL2_SAMEINSTRUMENT
    ld a,(hl)
    inc hl
    exx
    ld e,a
    ld d,0
    ld hl,(PLY_AKG_InstrumentsTable+1)
    add hl,de
    add hl,de
    ld sp,hl
    pop hl
    ld a,(hl)
    inc hl
    ld (PLY_AKG_CHANNEL2_INSTRUMENTORIGINALSPEED+1),a
    ld (PLY_AKG_Channel2_PtInstrument+1),hl
    ld (PLY_AKG_CHANNEL2_SAMEINSTRUMENT+1),hl
    exx
PLY_AKG_CHANNEL2_AFTERINSTRUMENT:
    ex de,hl
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_CHANNEL2_PITCHTABLE_END+1),hl
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL2_PITCHTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL2_INSTRUMENTSTEP+2),a
PLY_AKG_CHANNEL2_INSTRUMENTORIGINALSPEED:
    ld a,0
    ld (PLY_AKG_CHANNEL2_INSTRUMENTSPEED+1),a
    ld a,183
    ld (PLY_AKG_Channel2_IsPitch),a
    ld a,(PLY_AKG_CHANNEL2_ARPEGGIOBASESPEED)
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLESPEED),a
    ld a,(PLY_AKG_CHANNEL2_PITCHBASESPEED)
    ld (PLY_AKG_CHANNEL2_PITCHTABLESPEED),a
    ld hl,(PLY_AKG_CHANNEL2_ARPEGGIOTABLEBASE)
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLE+1),hl
    ld hl,(PLY_AKG_CHANNEL2_PITCHTABLEBASE)
    ld (PLY_AKG_CHANNEL2_PITCHTABLE+1),hl
    ex de,hl
    rl c
    jp c,PLY_AKG_CHANNEL2_READEFFECTS
PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER:
    ld (PLY_AKG_CHANNEL2_READTRACK+1),hl
PLY_AKG_CHANNEL2_READCELLEND:
PLY_AKG_Channel3_WaitCounter:
    ld a,0
    sub 1
    jr c,PLY_AKG_CHANNEL3_READTRACK
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    jp PLY_AKG_CHANNEL3_READCELLEND
PLY_AKG_CHANNEL3_READTRACK:
PLY_AKG_Channel3_PtTrack:
    ld hl,0
    ld c,(hl)
    inc hl
    ld a,c
    and 63
    cp 60
    jr c,PLY_AKG_CHANNEL3_NOTE
    sub 60
    jp z,PLY_AKG_CHANNEL2_READEFFECTSEND
    dec a
    jr z,PLY_AKG_CHANNEL3_WAIT
    dec a
    jr z,PLY_AKG_CHANNEL3_SMALLWAIT
    ld a,(hl)
    inc hl
    jr PLY_AKG_CHANNEL3_AFTERNOTEKNOWN
PLY_AKG_CHANNEL3_SMALLWAIT:
    ld a,c
    rlca
    rlca
    and 3
    inc a
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    jr PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL3_WAIT:
    ld a,(hl)
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    inc hl
    jr PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL3_SAMEINSTRUMENT:
PLY_AKG_CHANNEL3_PTBASEINSTRUMENT:
    ld de,0
    ld (PLY_AKG_Channel3_PtInstrument+1),de
    jr PLY_AKG_CHANNEL3_AFTERINSTRUMENT
PLY_AKG_CHANNEL3_NOTE:
    ld b,a
    ld a,(PLY_AKG_CHANNEL1_NOTE+1)
    add a,b
PLY_AKG_CHANNEL3_AFTERNOTEKNOWN:
PLY_AKG_Channel3_Transposition:
    add a,0
    ld (PLY_AKG_CHANNEL3_TRACKNOTE+1),a
    rl c
    jr nc,PLY_AKG_CHANNEL3_SAMEINSTRUMENT
    ld a,(hl)
    inc hl
    exx
    ld e,a
    ld d,0
    ld hl,(PLY_AKG_InstrumentsTable+1)
    add hl,de
    add hl,de
    ld sp,hl
    pop hl
    ld a,(hl)
    inc hl
    ld (PLY_AKG_CHANNEL3_INSTRUMENTORIGINALSPEED+1),a
    ld (PLY_AKG_Channel3_PtInstrument+1),hl
    ld (PLY_AKG_CHANNEL3_SAMEINSTRUMENT+1),hl
    exx
PLY_AKG_CHANNEL3_AFTERINSTRUMENT:
    ex de,hl
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_CHANNEL3_PITCHTABLE_END+1),hl
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL3_PITCHTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL3_INSTRUMENTSTEP+2),a
PLY_AKG_CHANNEL3_INSTRUMENTORIGINALSPEED:
    ld a,0
    ld (PLY_AKG_CHANNEL3_INSTRUMENTSPEED+1),a
    ld a,183
    ld (PLY_AKG_Channel3_IsPitch),a
    ld a,(PLY_AKG_CHANNEL3_ARPEGGIOBASESPEED)
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLESPEED),a
    ld a,(PLY_AKG_CHANNEL3_PITCHBASESPEED)
    ld (PLY_AKG_CHANNEL3_PITCHTABLESPEED),a
    ld hl,(PLY_AKG_CHANNEL3_ARPEGGIOTABLEBASE)
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLE+1),hl
    ld hl,(PLY_AKG_CHANNEL3_PITCHTABLEBASE)
    ld (PLY_AKG_CHANNEL3_PITCHTABLE+1),hl
    ex de,hl
    rl c
    jp c,PLY_AKG_CHANNEL3_READEFFECTS
PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER:
    ld (PLY_AKG_CHANNEL3_READTRACK+1),hl
PLY_AKG_CHANNEL3_READCELLEND:
PLY_AKG_CurrentSpeed:
    ld a,0
PLY_AKG_SetSpeedBeforePlayStreams:
    ld (PLY_AKG_TickDecreasingCounter+1),a
PLY_AKG_Channel1_InvertedVolumeInteger equ $+2
PLY_AKG_Channel1_InvertedVolumeIntegerAndDecimal:
    ld hl,0
PLY_AKG_Channel1_IsVolumeSlide:
    or a
    jr nc,PLY_AKG_CHANNEL1_VOLUMESLIDE_END
PLY_AKG_Channel1_VolumeSlideValue:
    ld de,0
    add hl,de
    bit 7,h
    jr z,PLY_AKG_CHANNEL1_VOLUMENOTOVERFLOW
    ld h,0
    jr PLY_AKG_CHANNEL1_VOLUMESETAGAIN
PLY_AKG_CHANNEL1_VOLUMENOTOVERFLOW:
    ld a,h
    cp 16
    jr c,PLY_AKG_CHANNEL1_VOLUMESETAGAIN
    ld h,15
PLY_AKG_CHANNEL1_VOLUMESETAGAIN:
    ld (PLY_AKG_Channel1_InvertedVolumeIntegerAndDecimal+1),hl
PLY_AKG_CHANNEL1_VOLUMESLIDE_END:
    ld a,h
    ld (PLY_AKG_CHANNEL1_GENERATEDCURRENTINVERTEDVOLUME+1),a
    ld c,0
PLY_AKG_Channel1_IsArpeggioTable:
    or a
    jr nc,PLY_AKG_CHANNEL1_ARPEGGIOTABLE_END
PLY_AKG_Channel1_ArpeggioTable:
    ld hl,0
    ld a,(hl)
    cp 128
    jr nz,PLY_AKG_CHANNEL1_ARPEGGIOTABLE_AFTERLOOPTEST
    inc hl
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld a,(hl)
PLY_AKG_CHANNEL1_ARPEGGIOTABLE_AFTERLOOPTEST:
    ld c,a
    ld a,(PLY_AKG_Channel1_ArpeggioTableSpeed)
    ld d,a
PLY_AKG_Channel1_ArpeggioTableCurrentStep:
    ld a,0
    inc a
    cp d
    jr c,PLY_AKG_CHANNEL1_ARPEGGIOTABLE_BEFOREEND_SAVESTEP
    inc hl
    ld (PLY_AKG_Channel1_ArpeggioTable+1),hl
    xor a
PLY_AKG_CHANNEL1_ARPEGGIOTABLE_BEFOREEND_SAVESTEP:
    ld (PLY_AKG_Channel1_ArpeggioTableCurrentStep+1),a
PLY_AKG_CHANNEL1_ARPEGGIOTABLE_END:
    ld de,0
PLY_AKG_Channel1_IsPitchTable:
    or a
    jr nc,PLY_AKG_CHANNEL1_PITCHTABLE_END
PLY_AKG_Channel1_PitchTable:
    ld sp,0
    pop de
    pop hl
    ld a,(PLY_AKG_Channel1_PitchTableSpeed)
    ld b,a
PLY_AKG_Channel1_PitchTableCurrentStep:
    ld a,0
    inc a
    cp b
    jr c,PLY_AKG_CHANNEL1_PITCHTABLE_BEFOREEND_SAVESTEP
    ld (PLY_AKG_Channel1_PitchTable+1),hl
    xor a
PLY_AKG_CHANNEL1_PITCHTABLE_BEFOREEND_SAVESTEP:
    ld (PLY_AKG_Channel1_PitchTableCurrentStep+1),a
PLY_AKG_CHANNEL1_PITCHTABLE_END:
PLY_AKG_Channel1_Pitch:
    ld hl,0
PLY_AKG_Channel1_IsPitch:
    or a
    jr nc,PLY_AKG_CHANNEL1_PITCH_END
    db 221
    db 105
PLY_AKG_Channel1_PitchTrack:
    ld bc,0
    or a
PLY_AKG_Channel1_PitchTrackAddOrSbc_16bits:
    nop
    add hl,bc
PLY_AKG_CHANNEL1_PITCHTRACKDECIMALCOUNTER:
    ld a,0
PLY_AKG_Channel1_PitchTrackDecimalValue equ $+1
PLY_AKG_Channel1_PitchTrackDecimalInstr:
    add a,0
    ld (PLY_AKG_CHANNEL1_PITCHTRACKDECIMALCOUNTER+1),a
    jr nc,PLY_AKG_CHANNEL1_PITCHNOCARRY
PLY_AKG_Channel1_PitchTrackIntegerAddOrSub:
    inc hl
PLY_AKG_CHANNEL1_PITCHNOCARRY:
    ld (PLY_AKG_CHANNEL1_PITCHTABLE_END+1),hl
PLY_AKG_Channel1_SoundStream_RelativeModifierAddress:
PLY_AKG_Channel1_GlideDirection:
    ld a,0
    or a
    jr z,PLY_AKG_CHANNEL1_GLIDE_END
    ld (PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES+1),hl
    ld c,l
    ld b,h
    ex af,af'
    ld a,(PLY_AKG_Channel1_TrackNote+1)
    add a,a
    ld l,a
    ex af,af'
    ld h,0
    ld sp,PLY_AKG_PeriodTable
    add hl,sp
    ld sp,hl
    pop hl
    dec sp
    dec sp
    add hl,bc
PLY_AKG_Channel1_GlideToReach:
    ld bc,0
    rra
    jr nc,PLY_AKG_CHANNEL1_GLIDEDOWNCHECK
    or a
    sbc hl,bc
    jr nc,PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES
    jr PLY_AKG_CHANNEL1_GLIDEOVER
PLY_AKG_CHANNEL1_GLIDEDOWNCHECK:
    sbc hl,bc
    jr c,PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES
PLY_AKG_CHANNEL1_GLIDEOVER:
    ld l,c
    ld h,b
    pop bc
    or a
    sbc hl,bc
    ld (PLY_AKG_CHANNEL1_PITCHTABLE_END+1),hl
    ld a,183
    ld (PLY_AKG_Channel1_IsPitch),a
    jr PLY_AKG_CHANNEL1_GLIDE_END
PLY_AKG_Channel1_ArpeggioTableSpeed:
    db 0
PLY_AKG_Channel1_ArpeggioBaseSpeed:
    db 0
PLY_AKG_Channel1_ArpeggioTableBase:
    db 0
    db 0
PLY_AKG_Channel1_PitchTableSpeed:
    db 0
PLY_AKG_Channel1_PitchBaseSpeed:
    db 0
PLY_AKG_Channel1_PitchTableBase:
    db 0
    db 0
PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES:
PLY_AKG_CHANNEL1_GLIDE_BEFOREEND:
PLY_AKG_CHANNEL1_GLIDE_SAVEHL:
    ld hl,0
PLY_AKG_CHANNEL1_GLIDE_END:
    db 221
    db 77
PLY_AKG_CHANNEL1_PITCH_END:
    add hl,de
    ld (PLY_AKG_Channel1_PlayInstrument_RelativeModifierAddress+1),hl
    ld a,c
    ld (PLY_AKG_CHANNEL1_GENERATEDCURRENTARPNOTE+1),a
PLY_AKG_CHANNEL2_INVERTEDVOLUMEINTEGER equ $+2
PLY_AKG_Channel2_InvertedVolumeIntegerAndDecimal:
    ld hl,0
PLY_AKG_Channel2_IsVolumeSlide:
    or a
    jr nc,PLY_AKG_CHANNEL2_VOLUMESLIDE_END
PLY_AKG_CHANNEL2_VOLUMESLIDEVALUE:
    ld de,0
    add hl,de
    bit 7,h
    jr z,PLY_AKG_CHANNEL2_VOLUMENOTOVERFLOW
    ld h,0
    jr PLY_AKG_CHANNEL2_VOLUMESETAGAIN
PLY_AKG_CHANNEL2_VOLUMENOTOVERFLOW:
    ld a,h
    cp 16
    jr c,PLY_AKG_CHANNEL2_VOLUMESETAGAIN
    ld h,15
PLY_AKG_CHANNEL2_VOLUMESETAGAIN:
    ld (PLY_AKG_Channel2_InvertedVolumeIntegerAndDecimal+1),hl
PLY_AKG_CHANNEL2_VOLUMESLIDE_END:
    ld a,h
    ld (PLY_AKG_CHANNEL2_GENERATEDCURRENTINVERTEDVOLUME+1),a
    ld c,0
PLY_AKG_Channel2_IsArpeggioTable:
    or a
    jr nc,PLY_AKG_CHANNEL2_ARPEGGIOTABLE_END
PLY_AKG_CHANNEL2_ARPEGGIOTABLE:
    ld hl,0
    ld a,(hl)
    cp 128
    jr nz,PLY_AKG_CHANNEL2_ARPEGGIOTABLE_AFTERLOOPTEST
    inc hl
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld a,(hl)
PLY_AKG_CHANNEL2_ARPEGGIOTABLE_AFTERLOOPTEST:
    ld c,a
    ld a,(PLY_AKG_CHANNEL2_ARPEGGIOTABLESPEED)
    ld d,a
PLY_AKG_CHANNEL2_ARPEGGIOTABLECURRENTSTEP:
    ld a,0
    inc a
    cp d
    jr c,PLY_AKG_CHANNEL2_ARPEGGIOTABLE_BEFOREEND_SAVESTEP
    inc hl
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLE+1),hl
    xor a
PLY_AKG_CHANNEL2_ARPEGGIOTABLE_BEFOREEND_SAVESTEP:
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL2_ARPEGGIOTABLE_END:
    ld de,0
PLY_AKG_Channel2_IsPitchTable:
    or a
    jr nc,PLY_AKG_CHANNEL2_PITCHTABLE_END
PLY_AKG_CHANNEL2_PITCHTABLE:
    ld sp,0
    pop de
    pop hl
    ld a,(PLY_AKG_CHANNEL2_PITCHTABLESPEED)
    ld b,a
PLY_AKG_CHANNEL2_PITCHTABLECURRENTSTEP:
    ld a,0
    inc a
    cp b
    jr c,PLY_AKG_CHANNEL2_PITCHTABLE_BEFOREEND_SAVESTEP
    ld (PLY_AKG_CHANNEL2_PITCHTABLE+1),hl
    xor a
PLY_AKG_CHANNEL2_PITCHTABLE_BEFOREEND_SAVESTEP:
    ld (PLY_AKG_CHANNEL2_PITCHTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL2_PITCHTABLE_END:
PLY_AKG_Channel2_Pitch:
    ld hl,0
PLY_AKG_Channel2_IsPitch:
    or a
    jr nc,PLY_AKG_CHANNEL2_PITCH_END
    db 221
    db 105
PLY_AKG_CHANNEL2_PITCHTRACK:
    ld bc,0
    or a
PLY_AKG_CHANNEL2_PITCHTRACKADDORSBC_16BITS:
    nop
    add hl,bc
PLY_AKG_CHANNEL2_PITCHTRACKDECIMALCOUNTER:
    ld a,0
PLY_AKG_CHANNEL2_PITCHTRACKDECIMALVALUE equ $+1
PLY_AKG_CHANNEL2_PITCHTRACKDECIMALINSTR:
    add a,0
    ld (PLY_AKG_CHANNEL2_PITCHTRACKDECIMALCOUNTER+1),a
    jr nc,PLY_AKG_CHANNEL2_PITCHNOCARRY
PLY_AKG_CHANNEL2_PITCHTRACKINTEGERADDORSUB:
    inc hl
PLY_AKG_CHANNEL2_PITCHNOCARRY:
    ld (PLY_AKG_CHANNEL2_PITCHTABLE_END+1),hl
PLY_AKG_CHANNEL2_SOUNDSTREAM_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL2_GLIDEDIRECTION:
    ld a,0
    or a
    jr z,PLY_AKG_CHANNEL2_GLIDE_END
    ld (PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES+1),hl
    ld c,l
    ld b,h
    ex af,af'
    ld a,(PLY_AKG_CHANNEL2_TRACKNOTE+1)
    add a,a
    ld l,a
    ex af,af'
    ld h,0
    ld sp,PLY_AKG_PeriodTable
    add hl,sp
    ld sp,hl
    pop hl
    dec sp
    dec sp
    add hl,bc
PLY_AKG_CHANNEL2_GLIDETOREACH:
    ld bc,0
    rra
    jr nc,PLY_AKG_CHANNEL2_GLIDEDOWNCHECK
    or a
    sbc hl,bc
    jr nc,PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES
    jr PLY_AKG_CHANNEL2_GLIDEOVER
PLY_AKG_CHANNEL2_GLIDEDOWNCHECK:
    sbc hl,bc
    jr c,PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES
PLY_AKG_CHANNEL2_GLIDEOVER:
    ld l,c
    ld h,b
    pop bc
    or a
    sbc hl,bc
    ld (PLY_AKG_CHANNEL2_PITCHTABLE_END+1),hl
    ld a,183
    ld (PLY_AKG_Channel2_IsPitch),a
    jr PLY_AKG_CHANNEL2_GLIDE_END
PLY_AKG_CHANNEL2_ARPEGGIOTABLESPEED:
    db 0
PLY_AKG_CHANNEL2_ARPEGGIOBASESPEED:
    db 0
PLY_AKG_CHANNEL2_ARPEGGIOTABLEBASE:
    db 0
    db 0
PLY_AKG_CHANNEL2_PITCHTABLESPEED:
    db 0
PLY_AKG_CHANNEL2_PITCHBASESPEED:
    db 0
PLY_AKG_CHANNEL2_PITCHTABLEBASE:
    db 0
    db 0
PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES:
PLY_AKG_CHANNEL2_GLIDE_BEFOREEND:
PLY_AKG_CHANNEL2_GLIDE_SAVEHL:
    ld hl,0
PLY_AKG_CHANNEL2_GLIDE_END:
    db 221
    db 77
PLY_AKG_CHANNEL2_PITCH_END:
    add hl,de
    ld (PLY_AKG_CHANNEL2_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS+1),hl
    ld a,c
    ld (PLY_AKG_CHANNEL2_GENERATEDCURRENTARPNOTE+1),a
PLY_AKG_CHANNEL3_INVERTEDVOLUMEINTEGER equ $+2
PLY_AKG_Channel3_InvertedVolumeIntegerAndDecimal:
    ld hl,0
PLY_AKG_Channel3_IsVolumeSlide:
    or a
    jr nc,PLY_AKG_CHANNEL3_VOLUMESLIDE_END
PLY_AKG_CHANNEL3_VOLUMESLIDEVALUE:
    ld de,0
    add hl,de
    bit 7,h
    jr z,PLY_AKG_CHANNEL3_VOLUMENOTOVERFLOW
    ld h,0
    jr PLY_AKG_CHANNEL3_VOLUMESETAGAIN
PLY_AKG_CHANNEL3_VOLUMENOTOVERFLOW:
    ld a,h
    cp 16
    jr c,PLY_AKG_CHANNEL3_VOLUMESETAGAIN
    ld h,15
PLY_AKG_CHANNEL3_VOLUMESETAGAIN:
    ld (PLY_AKG_Channel3_InvertedVolumeIntegerAndDecimal+1),hl
PLY_AKG_CHANNEL3_VOLUMESLIDE_END:
    ld a,h
    ld (PLY_AKG_CHANNEL3_GENERATEDCURRENTINVERTEDVOLUME+1),a
    ld c,0
PLY_AKG_Channel3_IsArpeggioTable:
    or a
    jr nc,PLY_AKG_CHANNEL3_ARPEGGIOTABLE_END
PLY_AKG_CHANNEL3_ARPEGGIOTABLE:
    ld hl,0
    ld a,(hl)
    cp 128
    jr nz,PLY_AKG_CHANNEL3_ARPEGGIOTABLE_AFTERLOOPTEST
    inc hl
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld a,(hl)
PLY_AKG_CHANNEL3_ARPEGGIOTABLE_AFTERLOOPTEST:
    ld c,a
    ld a,(PLY_AKG_CHANNEL3_ARPEGGIOTABLESPEED)
    ld d,a
PLY_AKG_CHANNEL3_ARPEGGIOTABLECURRENTSTEP:
    ld a,0
    inc a
    cp d
    jr c,PLY_AKG_CHANNEL3_ARPEGGIOTABLE_BEFOREEND_SAVESTEP
    inc hl
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLE+1),hl
    xor a
PLY_AKG_CHANNEL3_ARPEGGIOTABLE_BEFOREEND_SAVESTEP:
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL3_ARPEGGIOTABLE_END:
    ld de,0
PLY_AKG_Channel3_IsPitchTable:
    or a
    jr nc,PLY_AKG_CHANNEL3_PITCHTABLE_END
PLY_AKG_CHANNEL3_PITCHTABLE:
    ld sp,0
    pop de
    pop hl
    ld a,(PLY_AKG_CHANNEL3_PITCHTABLESPEED)
    ld b,a
PLY_AKG_CHANNEL3_PITCHTABLECURRENTSTEP:
    ld a,0
    inc a
    cp b
    jr c,PLY_AKG_CHANNEL3_PITCHTABLE_BEFOREEND_SAVESTEP
    ld (PLY_AKG_CHANNEL3_PITCHTABLE+1),hl
    xor a
PLY_AKG_CHANNEL3_PITCHTABLE_BEFOREEND_SAVESTEP:
    ld (PLY_AKG_CHANNEL3_PITCHTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL3_PITCHTABLE_END:
PLY_AKG_Channel3_Pitch:
    ld hl,0
PLY_AKG_Channel3_IsPitch:
    or a
    jr nc,PLY_AKG_CHANNEL3_PITCH_END
    db 221
    db 105
PLY_AKG_CHANNEL3_PITCHTRACK:
    ld bc,0
    or a
PLY_AKG_CHANNEL3_PITCHTRACKADDORSBC_16BITS:
    nop
    add hl,bc
PLY_AKG_CHANNEL3_PITCHTRACKDECIMALCOUNTER:
    ld a,0
PLY_AKG_CHANNEL3_PITCHTRACKDECIMALVALUE equ $+1
PLY_AKG_CHANNEL3_PITCHTRACKDECIMALINSTR:
    add a,0
    ld (PLY_AKG_CHANNEL3_PITCHTRACKDECIMALCOUNTER+1),a
    jr nc,PLY_AKG_CHANNEL3_PITCHNOCARRY
PLY_AKG_CHANNEL3_PITCHTRACKINTEGERADDORSUB:
    inc hl
PLY_AKG_CHANNEL3_PITCHNOCARRY:
    ld (PLY_AKG_CHANNEL3_PITCHTABLE_END+1),hl
PLY_AKG_CHANNEL3_SOUNDSTREAM_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL3_GLIDEDIRECTION:
    ld a,0
    or a
    jr z,PLY_AKG_CHANNEL3_GLIDE_END
    ld (PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES+1),hl
    ld c,l
    ld b,h
    ex af,af'
    ld a,(PLY_AKG_CHANNEL3_TRACKNOTE+1)
    add a,a
    ld l,a
    ex af,af'
    ld h,0
    ld sp,PLY_AKG_PeriodTable
    add hl,sp
    ld sp,hl
    pop hl
    dec sp
    dec sp
    add hl,bc
PLY_AKG_CHANNEL3_GLIDETOREACH:
    ld bc,0
    rra
    jr nc,PLY_AKG_CHANNEL3_GLIDEDOWNCHECK
    or a
    sbc hl,bc
    jr nc,PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES
    jr PLY_AKG_CHANNEL3_GLIDEOVER
PLY_AKG_CHANNEL3_GLIDEDOWNCHECK:
    sbc hl,bc
    jr c,PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES
PLY_AKG_CHANNEL3_GLIDEOVER:
    ld l,c
    ld h,b
    pop bc
    or a
    sbc hl,bc
    ld (PLY_AKG_CHANNEL3_PITCHTABLE_END+1),hl
    ld a,183
    ld (PLY_AKG_Channel3_IsPitch),a
    jr PLY_AKG_CHANNEL3_GLIDE_END
PLY_AKG_CHANNEL3_ARPEGGIOTABLESPEED:
    db 0
PLY_AKG_CHANNEL3_ARPEGGIOBASESPEED:
    db 0
PLY_AKG_CHANNEL3_ARPEGGIOTABLEBASE:
    db 0
    db 0
PLY_AKG_CHANNEL3_PITCHTABLESPEED:
    db 0
PLY_AKG_CHANNEL3_PITCHBASESPEED:
    db 0
PLY_AKG_CHANNEL3_PITCHTABLEBASE:
    db 0
    db 0
PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES:
PLY_AKG_CHANNEL3_GLIDE_BEFOREEND:
PLY_AKG_CHANNEL3_GLIDE_SAVEHL:
    ld hl,0
PLY_AKG_CHANNEL3_GLIDE_END:
    db 221
    db 77
PLY_AKG_CHANNEL3_PITCH_END:
    add hl,de
    ld (PLY_AKG_CHANNEL3_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS+1),hl
    ld a,c
    ld (PLY_AKG_CHANNEL3_GENERATEDCURRENTARPNOTE+1),a
    ld sp,(PLY_AKG_PSGReg13_End+1)
PLY_AKG_Channel1_PlayInstrument_RelativeModifierAddress:
PLY_AKG_CHANNEL1_GENERATEDCURRENTPITCH:
    ld hl,0
PLY_AKG_Channel1_TrackNote:
    ld a,0
PLY_AKG_CHANNEL1_GENERATEDCURRENTARPNOTE:
    add a,0
    ld e,a
    ld d,0
    exx
PLY_AKG_CHANNEL1_INSTRUMENTSTEP:
    db 253
    db 46
    db 0
PLY_AKG_Channel1_PtInstrument:
    ld hl,0
PLY_AKG_CHANNEL1_GENERATEDCURRENTINVERTEDVOLUME:
    ld de,57359
    call PLY_AKG_ReadInstrumentCell
    db 253
    db 125
    inc a
PLY_AKG_Channel1_InstrumentSpeed:
    cp 0
    jr c,PLY_AKG_CHANNEL1_SETINSTRUMENTSTEP
    ld (PLY_AKG_Channel1_PtInstrument+1),hl
    xor a
PLY_AKG_CHANNEL1_SETINSTRUMENTSTEP:
    ld (PLY_AKG_CHANNEL1_INSTRUMENTSTEP+2),a
    ld a,e
    ld (PLY_AKG_PSGReg8),a
    srl d
    exx
    ld (PLY_AKG_PSGReg01_Instr+1),hl
PLY_AKG_CHANNEL2_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL2_GENERATEDCURRENTPITCH:
    ld hl,0
PLY_AKG_CHANNEL2_TRACKNOTE:
    ld a,0
PLY_AKG_CHANNEL2_GENERATEDCURRENTARPNOTE:
    add a,0
    ld e,a
    ld d,0
    exx
PLY_AKG_CHANNEL2_INSTRUMENTSTEP:
    db 253
    db 46
    db 0
PLY_AKG_Channel2_PtInstrument:
    ld hl,0
PLY_AKG_CHANNEL2_GENERATEDCURRENTINVERTEDVOLUME:
    ld e,15
    nop
    call PLY_AKG_ReadInstrumentCell
    db 253
    db 125
    inc a
PLY_AKG_CHANNEL2_INSTRUMENTSPEED:
    cp 0
    jr c,PLY_AKG_CHANNEL2_SETINSTRUMENTSTEP
    ld (PLY_AKG_Channel2_PtInstrument+1),hl
    xor a
PLY_AKG_CHANNEL2_SETINSTRUMENTSTEP:
    ld (PLY_AKG_CHANNEL2_INSTRUMENTSTEP+2),a
    ld a,e
    ld (PLY_AKG_PSGReg9),a
    srl d
    exx
    ld (PLY_AKG_PSGReg23_Instr+1),hl
PLY_AKG_CHANNEL3_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL3_GENERATEDCURRENTPITCH:
    ld hl,0
PLY_AKG_CHANNEL3_TRACKNOTE:
    ld a,0
PLY_AKG_CHANNEL3_GENERATEDCURRENTARPNOTE:
    add a,0
    ld e,a
    ld d,0
    exx
PLY_AKG_CHANNEL3_INSTRUMENTSTEP:
    db 253
    db 46
    db 0
PLY_AKG_Channel3_PtInstrument:
    ld hl,0
PLY_AKG_CHANNEL3_GENERATEDCURRENTINVERTEDVOLUME:
    ld e,15
    nop
    call PLY_AKG_ReadInstrumentCell
    db 253
    db 125
    inc a
PLY_AKG_CHANNEL3_INSTRUMENTSPEED:
    cp 0
    jr c,PLY_AKG_CHANNEL3_SETINSTRUMENTSTEP
    ld (PLY_AKG_Channel3_PtInstrument+1),hl
    xor a
PLY_AKG_CHANNEL3_SETINSTRUMENTSTEP:
    ld (PLY_AKG_CHANNEL3_INSTRUMENTSTEP+2),a
    ld a,e
    ld (PLY_AKG_PSGReg10),a
    ld a,d
    exx
    ld (PLY_AKG_PSGReg45_Instr+1),hl
    call PLY_AKG_PlaySoundEffectsStream
PLY_AKG_SendPSGRegisters:
    ld bc,63104
    ld e,192
    out (c),e
    exx
    ld bc,62465
PLY_AKG_PSGReg01_Instr:
    ld hl,0
    db 237
    db 113
    exx
    db 237
    db 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGReg23_Instr:
    ld hl,0
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGReg45_Instr:
    ld hl,0
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGReg6 equ $+1
PLY_AKG_PSGReg8 equ $+2
PLY_AKG_PSGReg6_8_Instr:
    ld hl,0
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),a
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGReg9 equ $+1
PLY_AKG_PSGReg10 equ $+2
PLY_AKG_PSGReg9_10_Instr:
    ld hl,0
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGHardwarePeriod_Instr:
    ld hl,0
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGReg13_OldValue:
    ld a,255
PLY_AKG_Retrig:
    or 0
PLY_AKG_PSGReg13_Instr:
    ld l,0
    cp l
    jr z,PLY_AKG_PSGReg13_End
    ld a,l
    ld (PLY_AKG_PSGReg13_OldValue+1),a
    inc c
    out (c),c
    exx
    db 237
    db 113
    exx
    out (c),a
    exx
    out (c),c
    out (c),e
    xor a
    ld (PLY_AKG_Retrig+1),a
PLY_AKG_PSGReg13_End:
PLY_AKG_SaveSP:
    ld sp,0
    ret
PLY_AKG_CHANNEL1_MAYBEEFFECTS:
    ld (PLY_AKG_EventTrack_End+1),a
    bit 6,c
    jp z,PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL1_READEFFECTS:
    ld iy,PLY_AKG_Channel1_SoundStream_RelativeModifierAddress
    ld ix,PLY_AKG_Channel1_PlayInstrument_RelativeModifierAddress
    ld de,PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
    jr PLY_AKG_Channel3_ReadEffectsEnd
PLY_AKG_CHANNEL1_READEFFECTSEND:
PLY_AKG_CHANNEL2_MAYBEEFFECTS:
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    bit 6,c
    jp z,PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL2_READEFFECTS:
    ld iy,PLY_AKG_CHANNEL2_SOUNDSTREAM_RELATIVEMODIFIERADDRESS
    ld ix,PLY_AKG_CHANNEL2_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS
    ld de,PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
    jr PLY_AKG_Channel3_ReadEffectsEnd
PLY_AKG_CHANNEL2_READEFFECTSEND:
PLY_AKG_CHANNEL3_MAYBEEFFECTS:
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    bit 6,c
    jp z,PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL3_READEFFECTS:
    ld iy,PLY_AKG_CHANNEL3_SOUNDSTREAM_RELATIVEMODIFIERADDRESS
    ld ix,PLY_AKG_CHANNEL3_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS
    ld de,PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_Channel3_ReadEffectsEnd:
PLY_AKG_Channel_ReadEffects:
    ld (PLY_AKG_Channel_ReadEffects_EndJump+1),de
    ex de,hl
    ld a,(de)
    inc de
    sla a
    jr c,PLY_AKG_Channel_ReadEffects_RelativeAddress
    exx
    ld l,a
    ld h,0
PLY_AKG_Channel_ReadEffects_EffectBlocks1:
    ld de,0
    add hl,de
    ld e,(hl)
    inc hl
    ld d,(hl)
PLY_AKG_Channel_RE_EffectAddressKnown:
    ld a,(de)
    inc de
    ld (PLY_AKG_Channel_RE_EffectReturn+1),a
    and 254
    ld l,a
    ld h,0
    ld sp,PLY_AKG_EffectTable
    add hl,sp
    ld sp,hl
    ret
PLY_AKG_Channel_RE_EffectReturn:
PLY_AKG_Channel_RE_ReadNextEffectInBlock:
    ld a,0
    rra
    jr c,PLY_AKG_Channel_RE_EffectAddressKnown
    exx
    ex de,hl
PLY_AKG_Channel_ReadEffects_EndJump:
    jp 0
PLY_AKG_Channel_ReadEffects_RelativeAddress:
    srl a
    exx
    ld h,a
    exx
    ld a,(de)
    inc de
    exx
    ld l,a
PLY_AKG_Channel_ReadEffects_EffectBlocks2:
    ld de,0
    add hl,de
    ex de,hl
    jr PLY_AKG_Channel_RE_EffectAddressKnown
PLY_AKG_ReadInstrumentCell:
    ld a,(hl)
    inc hl
    ld b,a
    rra
    jp c,PLY_AKG_S_Or_H_Or_SaH_Or_EndWithLoop
    rra
    jr c,PLY_AKG_StH_Or_EndWithoutLoop
    rra
    jr c,PLY_AKG_HardToSoft
PLY_AKG_NoSoftNoHard:
    and 15
    sub e
    jr nc,PLY_AKG_NoSoftNoHard+6
    xor a
    ld e,a
    rl b
    jr nc,PLY_AKG_NSNH_NoNoise
    ld a,(hl)
    inc hl
    ld (PLY_AKG_PSGReg6),a
    set 2,d
    res 5,d
    ret
PLY_AKG_NSNH_NoNoise:
    set 2,d
    ret
PLY_AKG_Soft:
    and 15
    sub e
    jr nc,PLY_AKG_SoftOnly_HardOnly_TestSimple_Common-1
    xor a
    ld e,a
PLY_AKG_SoftOnly_HardOnly_TestSimple_Common:
    rl b
    jr nc,PLY_AKG_S_NotSimple
    ld c,0
    jr PLY_AKG_S_AfterSimpleTest
PLY_AKG_S_NotSimple:
    ld b,(hl)
    ld c,b
    inc hl
PLY_AKG_S_AfterSimpleTest:
    call PLY_AKG_S_Or_H_CheckIfSimpleFirst_CalculatePeriod
    ld a,c
    and 31
    ret z
    ld (PLY_AKG_PSGReg6),a
    res 5,d
    ret
PLY_AKG_HardToSoft:
    call PLY_AKG_StoH_HToS_SandH_Common
    ld (PLY_AKG_HS_JumpRatio+1),a
    ld a,b
    exx
    ld (PLY_AKG_PSGHardwarePeriod_Instr+1),hl
PLY_AKG_HS_JumpRatio:
    jr PLY_AKG_HS_JumpRatio+2
    sla l
    rl h
    sla l
    rl h
    sla l
    rl h
    sla l
    rl h
    sla l
    rl h
    sla l
    rl h
    sla l
    rl h
    rla
    jr nc,PLY_AKG_SH_NoSoftwarePitchShift
    exx
    ld a,(hl)
    inc hl
    exx
    add a,l
    ld l,a
    exx
    ld a,(hl)
    inc hl
    exx
    adc a,h
    ld h,a
PLY_AKG_SH_NoSoftwarePitchShift:
    exx
    ret
PLY_AKG_EndWithoutLoop:
PLY_AKG_EmptyInstrumentDataPt:
    ld hl,0
    inc hl
    xor a
    ld b,a
    jr PLY_AKG_NoSoftNoHard
PLY_AKG_StH_Or_EndWithoutLoop:
    rra
    jr c,PLY_AKG_EndWithoutLoop
    call PLY_AKG_StoH_HToS_SandH_Common
    ld (PLY_AKG_SH_JumpRatio+1),a
    ld a,b
    exx
    ld e,l
    ld d,h
PLY_AKG_SH_JumpRatio:
    jr PLY_AKG_SH_JumpRatio+2
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    jr nc,PLY_AKG_SH_JumpRatioEnd
    inc hl
PLY_AKG_SH_JumpRatioEnd:
    rla
    jr nc,PLY_AKG_SH_NoHardwarePitchShift
    exx
    ld a,(hl)
    inc hl
    exx
    add a,l
    ld l,a
    exx
    ld a,(hl)
    inc hl
    exx
    adc a,h
    ld h,a
PLY_AKG_SH_NoHardwarePitchShift:
    ld (PLY_AKG_PSGHardwarePeriod_Instr+1),hl
    ex de,hl
    exx
    ret
PLY_AKG_S_Or_H_Or_SaH_Or_EndWithLoop:
    rra
    jr c,PLY_AKG_H_Or_EndWithLoop
    rra
    jp nc,PLY_AKG_Soft
    exx
    push hl
    push de
    exx
    call PLY_AKG_StoH_HToS_SandH_Common
    exx
    ld (PLY_AKG_PSGHardwarePeriod_Instr+1),hl
    pop de
    pop hl
    exx
    rl b
    jp PLY_AKG_S_Or_H_CheckIfSimpleFirst_CalculatePeriod
PLY_AKG_H_Or_EndWithLoop:
    rra
    jr c,PLY_AKG_EndWithLoop
    ld e,16
    rra
    jr nc,PLY_AKG_H_AfterRetrig
    ld c,a
    db 253
    db 125
    or a
    jr nz,PLY_AKG_H_RetrigEnd
    ld a,e
    ld (PLY_AKG_Retrig+1),a
PLY_AKG_H_RetrigEnd:
    ld a,c
PLY_AKG_H_AfterRetrig:
    and 7
    add a,8
    ld (PLY_AKG_PSGReg13_Instr+1),a
    call PLY_AKG_SoftOnly_HardOnly_TestSimple_Common
    exx
    ld (PLY_AKG_PSGHardwarePeriod_Instr+1),hl
    exx
    set 2,d
    ret
PLY_AKG_EndWithLoop:
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    jp PLY_AKG_ReadInstrumentCell
PLY_AKG_S_Or_H_CheckIfSimpleFirst_CalculatePeriod:
    jr nc,PLY_AKG_S_Or_H_NextByte
    exx
    ex de,hl
    add hl,hl
    ld bc,PLY_AKG_PeriodTable
    add hl,bc
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    add hl,de
    exx
    rl b
    rl b
    rl b
    ret
PLY_AKG_S_Or_H_NextByte:
    rl b
    jr c,PLY_AKG_S_Or_H_ForcedPeriod
    rl b
    jr nc,PLY_AKG_S_Or_H_AfterArpeggio
    ld a,(hl)
    inc hl
    exx
    add a,e
    ld e,a
    exx
PLY_AKG_S_Or_H_AfterArpeggio:
    rl b
    jr nc,PLY_AKG_S_Or_H_AfterPitch
    ld a,(hl)
    inc hl
    exx
    add a,l
    ld l,a
    exx
    ld a,(hl)
    inc hl
    exx
    adc a,h
    ld h,a
    exx
PLY_AKG_S_Or_H_AfterPitch:
    exx
    ex de,hl
    add hl,hl
    ld bc,PLY_AKG_PeriodTable
    add hl,bc
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    add hl,de
    exx
    ret
PLY_AKG_S_Or_H_ForcedPeriod:
    ld a,(hl)
    inc hl
    exx
    ld l,a
    exx
    ld a,(hl)
    inc hl
    exx
    ld h,a
    exx
    rl b
    rl b
    ret
PLY_AKG_StoH_HToS_SandH_Common:
    ld e,16
    rra
    jr nc,PLY_AKG_SHoHS_AfterRetrig
    ld c,a
    db 253
    db 125
    or a
    jr nz,PLY_AKG_SHoHS_RetrigEnd
    dec a
    ld (PLY_AKG_Retrig+1),a
PLY_AKG_SHoHS_RetrigEnd:
    ld a,c
PLY_AKG_SHoHS_AfterRetrig:
    and 7
    add a,8
    ld (PLY_AKG_PSGReg13_Instr+1),a
    rl b
    jr nc,PLY_AKG_SHoHS_AfterNoise
    ld a,(hl)
    inc hl
    ld (PLY_AKG_PSGReg6),a
    res 5,d
PLY_AKG_SHoHS_AfterNoise:
    ld c,(hl)
    ld b,c
    inc hl
    rl b
    call PLY_AKG_S_Or_H_CheckIfSimpleFirst_CalculatePeriod
    ld a,c
    rla
    rla
    and 28
    ret
PLY_AKG_EffectTable:
    dw PLY_AKG_Effect_ResetFullVolume
    dw PLY_AKG_Effect_Reset
    dw PLY_AKG_Effect_Volume
    dw PLY_AKG_Effect_ArpeggioTable
    dw PLY_AKG_Effect_ArpeggioTableStop
    dw PLY_AKG_Effect_PitchTable
    dw PLY_AKG_Effect_PitchTableStop
    dw PLY_AKG_Effect_VolumeSlide
    dw PLY_AKG_Effect_VolumeSlideStop
    dw PLY_AKG_Effect_PitchUp
    dw PLY_AKG_Effect_PitchDown
    dw PLY_AKG_Effect_PitchStop
    dw PLY_AKG_Effect_GlideWithNote
    dw PLY_AKG_Effect_Glide_ReadSpeed
    dw PLY_AKG_Effect_Legato
    dw PLY_AKG_Effect_ForceInstrumentSpeed
    dw PLY_AKG_Effect_ForceArpeggioSpeed
    dw PLY_AKG_Effect_ForcePitchSpeed
PLY_AKG_Effect_ResetFullVolume:
    xor a
    jr PLY_AKG_Effect_ResetVolume_AfterReading
PLY_AKG_Effect_Reset:
    ld a,(de)
    inc de
PLY_AKG_Effect_ResetVolume_AfterReading:
    ld (iy-123),a
    xor a
    ld (iy-26),a
    ld (iy-25),a
    ld a,183
    ld (iy-24),a
    ld (iy-52),a
    ld (iy-91),a
    ld (iy-122),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_Volume:
    ld a,(de)
    inc de
    ld (iy-123),a
    ld (iy-122),183
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_ArpeggioTable:
    ld a,(de)
    inc de
    ld l,a
    ld h,0
    add hl,hl
PLY_AKG_ArpeggiosTable:
    ld bc,0
    add hl,bc
    ld c,(hl)
    inc hl
    ld b,(hl)
    inc hl
    ld a,(bc)
    inc bc
    ld (iy+61),a
    ld (iy+62),a
    ld (iy-87),c
    ld (iy-86),b
    ld (iy+63),c
    ld (iy+64),b
    ld (iy-91),55
    xor a
    ld (iy-68),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_ArpeggioTableStop:
    ld (iy-91),183
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_PitchTable:
    ld a,(de)
    inc de
    ld l,a
    ld h,0
    add hl,hl
PLY_AKG_PitchesTable:
    ld bc,0
    add hl,bc
    ld c,(hl)
    inc hl
    ld b,(hl)
    inc hl
    ld a,(bc)
    inc bc
    ld (iy+65),a
    ld (iy+66),a
    ld (iy-48),c
    ld (iy-47),b
    ld (iy+67),c
    ld (iy+68),b
    ld (iy-52),55
    xor a
    ld (iy-39),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_PitchTableStop:
    ld (iy-52),183
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_VolumeSlide:
    ld a,(de)
    inc de
    ld (iy-118),a
    ld a,(de)
    inc de
    ld (iy-117),a
    ld (iy-122),55
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_VolumeSlideStop:
    ld (iy-122),183
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_PitchDown:
    ld (iy-15),0
    ld (iy-14),9
    ld (iy-11),198
    ld (iy-4),35
PLY_AKG_Effect_PitchUpDown_Common:
    ld (iy-24),55
    ld (iy+1),0
    ld a,(de)
    inc de
    ld (iy-10),a
    ld a,(de)
    inc de
    ld (iy-18),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_PitchUp:
    ld (iy-15),237
    ld (iy-14),66
    ld (iy-11),214
    ld (iy-4),43
    jr PLY_AKG_Effect_PitchUpDown_Common
PLY_AKG_Effect_PitchStop:
    ld (iy-24),183
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_GlideWithNote:
    ld a,(de)
    inc de
    ld (PLY_AKG_Effect_GlideWithNoteSaveDE+1),de
    add a,a
    ld l,a
    ld h,0
    ld bc,PLY_AKG_PeriodTable
    add hl,bc
    ld sp,hl
    pop de
    ld (iy+29),e
    ld (iy+30),d
    ld a,(ix+4)
    add a,a
    ld l,a
    ld h,0
    add hl,bc
    ld sp,hl
    pop hl
    ld c,(iy-26)
    ld b,(iy-25)
    add hl,bc
    or a
    sbc hl,de
PLY_AKG_Effect_GlideWithNoteSaveDE:
    ld de,0
    jr c,PLY_AKG_Effect_Glide_PitchDown
    ld (iy+1),1
    ld (iy-15),237
    ld (iy-14),66
    ld (iy-11),214
    ld (iy-4),43
PLY_AKG_Effect_Glide_ReadSpeed:
PLY_AKG_Effect_GlideSpeed:
    ld a,(de)
    inc de
    ld (iy-10),a
    ld a,(de)
    inc de
    ld (iy-18),a
    ld a,55
    ld (iy-24),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_Glide_PitchDown:
    ld (iy+1),2
    ld (iy-15),0
    ld (iy-14),9
    ld (iy-11),198
    ld (iy-4),35
    jr PLY_AKG_Effect_Glide_ReadSpeed
PLY_AKG_Effect_Legato:
    ld a,(de)
    inc de
    ld (ix+4),a
    ld a,183
    ld (iy-24),a
    xor a
    ld (iy-26),a
    ld (iy-25),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_ForceInstrumentSpeed:
    ld a,(de)
    inc de
    ld (ix+27),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_ForceArpeggioSpeed:
    ld a,(de)
    inc de
    ld (iy+61),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Effect_ForcePitchSpeed:
    ld a,(de)
    inc de
    ld (iy+65),a
    jp PLY_AKG_Channel_RE_EffectReturn
PLY_AKG_Event:
    db 0
PLY_AKG_PeriodTable:
    dw 3822
    dw 3608
    dw 3405
    dw 3214
    dw 3034
    dw 2863
    dw 2703
    dw 2551
    dw 2408
    dw 2273
    dw 2145
    dw 2025
    dw 1911
    dw 1804
    dw 1703
    dw 1607
    dw 1517
    dw 1432
    dw 1351
    dw 1276
    dw 1204
    dw 1136
    dw 1073
    dw 1012
    dw 956
    dw 902
    dw 851
    dw 804
    dw 758
    dw 716
    dw 676
    dw 638
    dw 602
    dw 568
    dw 536
    dw 506
    dw 478
    dw 451
    dw 426
    dw 402
    dw 379
    dw 358
    dw 338
    dw 319
    dw 301
    dw 284
    dw 268
    dw 253
    dw 239
    dw 225
    dw 213
    dw 201
    dw 190
    dw 179
    dw 169
    dw 159
    dw 150
    dw 142
    dw 134
    dw 127
    dw 119
    dw 113
    dw 106
    dw 100
    dw 95
    dw 89
    dw 84
    dw 80
    dw 75
    dw 71
    dw 67
    dw 63
    dw 60
    dw 56
    dw 53
    dw 50
    dw 47
    dw 45
    dw 42
    dw 40
    dw 38
    dw 36
    dw 34
    dw 32
    dw 30
    dw 28
    dw 27
    dw 25
    dw 24
    dw 22
    dw 21
    dw 20
    dw 19
    dw 18
    dw 17
    dw 16
    dw 15
    dw 14
    dw 13
    dw 13
    dw 12
    dw 11
    dw 11
    dw 10
    dw 9
    dw 9
    dw 8
    dw 8
    dw 7
    dw 7
    dw 7
    dw 6
    dw 6
    dw 6
    dw 5
    dw 5
    dw 5
    dw 4
    dw 4
    dw 4
    dw 4
    dw 4
    dw 3
    dw 3
    dw 3
    dw 3
    dw 3
    dw 2
