' sf_sfx.bas -- Arkos sound effects (AKX), converted by tools/aks2bas.py. Do not edit.
' Use: #include this at the top level, then pass @sf_sfx to SfxInit(@sf_sfx).

#ifndef __AKS_SF_SFX__
#define __AKS_SF_SFX__

asm
    jp __aks_sf_sfx_end
end asm
sf_sfx:
asm
    ; starfall sfx, Sound effects, format v2.0.

    ; Generated by Arkos Tracker 3.

sf_sfx_SoundEffects:
sf_sfx_SoundEffectsDisarkGenerateExternalLabel:

    ; The sound effects, starting at 1.
sf_sfx_SoundEffectsDisarkPointerRegionStart0:
    dw sf_sfx_SoundEffects_Sound1    ; Sound effect 1 at index 1.
    dw sf_sfx_SoundEffects_Sound2    ; Sound effect 2 at index 2.
    dw sf_sfx_SoundEffects_Sound3    ; Sound effect 3 at index 3.
    dw sf_sfx_SoundEffects_Sound4    ; Sound effect 4 at index 4.
sf_sfx_SoundEffectsDisarkPointerRegionEnd0:

sf_sfx_SoundEffectsDisarkByteRegionStart1:
    ; Sound effect 1.
sf_sfx_SoundEffects_Sound1:
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 126    ; Software period.

    db 57    ; Soft only. Volume: 14.
    dw 140    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 154    ; Software period.

    db 41    ; Soft only. Volume: 10.
    dw 169    ; Software period.

    db 33    ; Soft only. Volume: 8.
    dw 183    ; Software period.

    db 25    ; Soft only. Volume: 6.
    dw 197    ; Software period.

    db 17    ; Soft only. Volume: 4.
    dw 211    ; Software period.

    db 13    ; Soft only. Volume: 3.
    dw 225    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 239    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 2.
sf_sfx_SoundEffects_Sound2:
    db 0    ; Speed

    db 189    ; Soft only. Volume: 15.
    db 4    ; Noise: 4.
    dw 106    ; Software period.

    db 185    ; Soft only. Volume: 14.
    db 6    ; Noise: 6.
    dw 149    ; Software period.

    db 232    ; No soft, no hard. Volume: 13.
    db 8    ; Noise: 8.

    db 224    ; No soft, no hard. Volume: 12.
    db 10    ; Noise: 10.

    db 208    ; No soft, no hard. Volume: 10.
    db 13    ; Noise: 13.

    db 192    ; No soft, no hard. Volume: 8.
    db 15    ; Noise: 15.

    db 176    ; No soft, no hard. Volume: 6.
    db 18    ; Noise: 18.

    db 160    ; No soft, no hard. Volume: 4.
    db 22    ; Noise: 22.

    db 144    ; No soft, no hard. Volume: 2.
    db 26    ; Noise: 26.

    db 136    ; No soft, no hard. Volume: 1.
    db 30    ; Noise: 30.

    db 4    ; End of the sound effect.

    ; Sound effect 3.
sf_sfx_SoundEffects_Sound3:
    db 0    ; Speed

    db 189    ; Soft only. Volume: 15.
    db 6    ; Noise: 6.
    dw 847    ; Software period.

    db 189    ; Soft only. Volume: 15.
    db 7    ; Noise: 7.
    dw 875    ; Software period.

    db 185    ; Soft only. Volume: 14.
    db 8    ; Noise: 8.
    dw 904    ; Software period.

    db 185    ; Soft only. Volume: 14.
    db 9    ; Noise: 9.
    dw 932    ; Software period.

    db 181    ; Soft only. Volume: 13.
    db 10    ; Noise: 10.
    dw 960    ; Software period.

    db 181    ; Soft only. Volume: 13.
    db 11    ; Noise: 11.
    dw 989    ; Software period.

    db 177    ; Soft only. Volume: 12.
    db 12    ; Noise: 12.
    dw 1017    ; Software period.

    db 177    ; Soft only. Volume: 12.
    db 13    ; Noise: 13.
    dw 1046    ; Software period.

    db 173    ; Soft only. Volume: 11.
    db 14    ; Noise: 14.
    dw 1074    ; Software period.

    db 169    ; Soft only. Volume: 10.
    db 15    ; Noise: 15.
    dw 1102    ; Software period.

    db 165    ; Soft only. Volume: 9.
    db 16    ; Noise: 16.
    dw 1131    ; Software period.

    db 161    ; Soft only. Volume: 8.
    db 17    ; Noise: 17.
    dw 1159    ; Software period.

    db 157    ; Soft only. Volume: 7.
    db 18    ; Noise: 18.
    dw 1187    ; Software period.

    db 153    ; Soft only. Volume: 6.
    db 19    ; Noise: 19.
    dw 1216    ; Software period.

    db 149    ; Soft only. Volume: 5.
    db 20    ; Noise: 20.
    dw 1244    ; Software period.

    db 145    ; Soft only. Volume: 4.
    db 21    ; Noise: 21.
    dw 1273    ; Software period.

    db 141    ; Soft only. Volume: 3.
    db 22    ; Noise: 22.
    dw 1301    ; Software period.

    db 137    ; Soft only. Volume: 2.
    db 23    ; Noise: 23.
    dw 1329    ; Software period.

    db 133    ; Soft only. Volume: 1.
    db 24    ; Noise: 24.
    dw 1358    ; Software period.

    db 4    ; End of the sound effect.

    ; Sound effect 4.
sf_sfx_SoundEffects_Sound4:
    db 0    ; Speed

    db 53    ; Soft only. Volume: 13.
    dw 212    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 212    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 212    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 212    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 169    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 169    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 169    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 169    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 143    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 143    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 143    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 143    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 107    ; Software period.

    db 45    ; Soft only. Volume: 11.
    dw 107    ; Software period.

    db 33    ; Soft only. Volume: 8.
    dw 107    ; Software period.

    db 21    ; Soft only. Volume: 5.
    dw 107    ; Software period.

    db 13    ; Soft only. Volume: 3.
    dw 107    ; Software period.

    db 5    ; Soft only. Volume: 1.
    dw 107    ; Software period.

    db 4    ; End of the sound effect.

sf_sfx_SoundEffectsDisarkByteRegionEnd1:
__aks_sf_sfx_end:
end asm

#endif
