' Generated by img2cpc.py --spectrum --zx-sprite --name zx_icon games/shooter/assets/zx/zx_icon.png -o games/shooter/assets/zx/zx_icon.bas
' Source: games/shooter/assets/zx/zx_icon.png, 8x8 pixels, Spectrum
' spectrum 1x1 cells, 8 + 1 bytes
' Do not edit; regenerate with tools/build_assets.sh.

DIM zx_icon(7) AS UBYTE => { _
    $18, $18, $3C, $3C, $7E, $FF, $DB, $99 _
}
DIM zx_icon_attr(0) AS UBYTE => { _
    $78 _
}
CONST zx_icon_COLS AS UBYTE = 1
CONST zx_icon_ROWS AS UBYTE = 1
