' Generated by img2cpc.py --spectrum --zx-sprite --name zx_shots games/shooter/assets/zx/zx_shots.png -o games/shooter/assets/zx/zx_shots.bas
' Source: games/shooter/assets/zx/zx_shots.png, 16x32 pixels, Spectrum
' spectrum 2x4 cells, 64 + 8 bytes
' Do not edit; regenerate with tools/build_assets.sh.

DIM zx_shots(63) AS UBYTE => { _
    $C0, $C0, $C0, $C0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, _
    $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, _
    $C0, $C0, $C0, $C0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, _
    $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00 _
}
DIM zx_shots_attr(7) AS UBYTE => { _
    $47, $00, $00, $00, $47, $00, $00, $00 _
}
CONST zx_shots_COLS AS UBYTE = 2
CONST zx_shots_ROWS AS UBYTE = 4
